export type MedicalArea =
  | "Cardiovascular"
  | "Respiratorio"
  | "Neurológico"
  | "Endocrino-metabólico"
  | "Renal"
  | "Infeccioso"
  | "Gastrointestinal"
  | "Gineco-obstétrico"
  | "Pediatría"
  | "Urgencias y críticos";

export type MedicalUrgency = "baja" | "media" | "alta";

export type MedicalPathology = {
  id: string;
  name: string;
  area: MedicalArea;
  urgency: MedicalUrgency;
  summary: string;
  clinical_clues: string[];
  red_flags: string[];
  nursing_priorities: string[];
  diagnostic_support: string[];
};

export const MEDICAL_AREAS: MedicalArea[] = [
  "Cardiovascular",
  "Respiratorio",
  "Neurológico",
  "Endocrino-metabólico",
  "Renal",
  "Infeccioso",
  "Gastrointestinal",
  "Gineco-obstétrico",
  "Pediatría",
  "Urgencias y críticos",
];

const EXTRA_MEDICAL_PATHOLOGY_LIBRARY: MedicalPathology[] = [
  {
    id: "fibrilacion-auricular",
    name: "Fibrilación auricular",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Arritmia supraventricular frecuente con riesgo tromboembólico y descompensación hemodinámica.",
    clinical_clues: ["Palpitaciones", "disnea", "fatiga", "pulso irregular"],
    red_flags: ["Hipotensión", "dolor torácico", "síncope", "signos de ACV"],
    nursing_priorities: ["Monitor de ritmo", "control de frecuencia", "evaluar perfusión", "educar sobre adherencia anticoagulante"],
    diagnostic_support: ["ECG 12 derivaciones", "electrolitos", "función tiroidea", "ecocardiograma"],
  },
  {
    id: "embolia-pulmonar",
    name: "Embolia pulmonar",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Obstrucción arterial pulmonar con compromiso respiratorio y riesgo de inestabilidad.",
    clinical_clues: ["Disnea súbita", "dolor pleurítico", "taquicardia", "hipoxemia"],
    red_flags: ["Choque obstructivo", "síncope", "hipotensión", "deterioro respiratorio rápido"],
    nursing_priorities: ["Soporte de oxigenación", "monitor hemodinámico", "escalamiento temprano", "preparar anticoagulación según orden"],
    diagnostic_support: ["Angio-TAC pulmonar", "Dímero-D", "gasometría arterial", "ecografía venosa"],
  },
  {
    id: "trombosis-venosa-profunda",
    name: "Trombosis venosa profunda",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Formación de trombo venoso profundo con riesgo de embolia pulmonar.",
    clinical_clues: ["Edema unilateral", "dolor en pantorrilla", "aumento de temperatura local", "sensibilidad a la palpación"],
    red_flags: ["Disnea súbita", "dolor torácico", "hipoxemia", "taquicardia persistente"],
    nursing_priorities: ["Movilización segura", "vigilar progresión de edema", "educar sobre anticoagulación", "control de dolor"],
    diagnostic_support: ["Eco Doppler venoso", "Dímero-D", "perfil de coagulación", "estratificación de riesgo"],
  },
  {
    id: "endocarditis-infecciosa",
    name: "Endocarditis infecciosa",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Infección valvular con riesgo de embolización y falla cardiaca.",
    clinical_clues: ["Fiebre persistente", "soplo nuevo", "fatiga intensa", "fenómenos embólicos"],
    red_flags: ["Sepsis", "insuficiencia cardiaca aguda", "embolia cerebral", "bloqueo AV"],
    nursing_priorities: ["Control térmico y hemodinámico", "vigilancia neurológica", "adherencia antibiótica", "prevención de complicaciones embólicas"],
    diagnostic_support: ["Hemocultivos seriados", "ecocardiograma", "PCR/VSG", "hemograma"],
  },
  {
    id: "miocarditis-aguda",
    name: "Miocarditis aguda",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Inflamación miocárdica aguda con deterioro de función ventricular y arritmias.",
    clinical_clues: ["Dolor torácico", "disnea", "palpitaciones", "fatiga progresiva"],
    red_flags: ["Arritmias inestables", "choque cardiogénico", "hipotensión", "congestión pulmonar"],
    nursing_priorities: ["Monitor cardíaco continuo", "evaluar perfusión", "control de balance hídrico", "escalamiento a críticos si deteriora"],
    diagnostic_support: ["ECG", "troponinas", "ecocardiograma", "resonancia cardíaca"],
  },
  {
    id: "shock-cardiogenico",
    name: "Shock cardiogénico",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Falla severa de bomba con hipoperfusión tisular y alta mortalidad.",
    clinical_clues: ["Hipotensión persistente", "oliguria", "piel fría", "alteración mental"],
    red_flags: ["Acidosis láctica", "hipoxemia", "arritmias malignas", "falla multiorgánica"],
    nursing_priorities: ["Soporte hemodinámico intensivo", "monitorización invasiva según protocolo", "control de diuresis", "coordinación de equipo crítico"],
    diagnostic_support: ["Lactato", "ecocardiograma urgente", "gasometría", "perfil orgánico"],
  },
  {
    id: "insuficiencia-respiratoria-aguda",
    name: "Insuficiencia respiratoria aguda",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Fracaso de oxigenación y/o ventilación con riesgo de hipoxia tisular.",
    clinical_clues: ["Disnea intensa", "taquipnea", "uso de músculos accesorios", "SatO2 baja"],
    red_flags: ["Alteración de conciencia", "fatiga respiratoria", "hipercapnia severa", "cianosis"],
    nursing_priorities: ["Asegurar vía aérea", "oxigenoterapia escalonada", "monitor gasométrico", "preparar soporte ventilatorio"],
    diagnostic_support: ["Gasometría arterial", "oximetría continua", "radiografía de tórax", "analítica básica"],
  },
  {
    id: "sdra",
    name: "Síndrome de distrés respiratorio agudo (SDRA)",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Insuficiencia respiratoria hipoxémica grave por daño alveolocapilar difuso.",
    clinical_clues: ["Hipoxemia refractaria", "infiltrados bilaterales", "taquipnea", "deterioro rápido"],
    red_flags: ["Requerimiento de ventilación mecánica", "shock asociado", "acidosis respiratoria", "falla multiorgánica"],
    nursing_priorities: ["Manejo ventilatorio protector", "posición prono según criterio", "prevención de neumonía asociada", "vigilancia hemodinámica"],
    diagnostic_support: ["Gasometría seriada", "radiografía/TC de tórax", "índice PaO2/FiO2", "lactato"],
  },
  {
    id: "neumotorax",
    name: "Neumotórax",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Acumulación de aire pleural con colapso pulmonar parcial o total.",
    clinical_clues: ["Dolor torácico súbito", "disnea", "hipoventilación unilateral", "taquicardia"],
    red_flags: ["Desviación traqueal", "hipotensión", "ingurgitación yugular", "deterioro rápido"],
    nursing_priorities: ["Reconocimiento inmediato", "preparar drenaje pleural", "oxigenoterapia", "monitor de signos vitales"],
    diagnostic_support: ["Radiografía de tórax", "ecografía pulmonar", "gasometría", "evaluación clínica seriada"],
  },
  {
    id: "derrame-pleural",
    name: "Derrame pleural",
    area: "Respiratorio",
    urgency: "media",
    summary: "Acumulación de líquido pleural con compromiso respiratorio variable.",
    clinical_clues: ["Disnea progresiva", "dolor pleurítico", "matidez a la percusión", "murmullo disminuido"],
    red_flags: ["Hipoxemia", "fiebre alta persistente", "inestabilidad hemodinámica", "empiema"],
    nursing_priorities: ["Vigilancia respiratoria", "preparar toracocentesis", "control de dolor", "educación sobre signos de alarma"],
    diagnostic_support: ["Ecografía pleural", "radiografía de tórax", "análisis de líquido pleural", "hemograma"],
  },
  {
    id: "tuberculosis-pulmonar",
    name: "Tuberculosis pulmonar",
    area: "Respiratorio",
    urgency: "media",
    summary: "Infección pulmonar por Mycobacterium tuberculosis con impacto respiratorio y comunitario.",
    clinical_clues: ["Tos crónica", "pérdida de peso", "sudoración nocturna", "hemoptisis"],
    red_flags: ["Insuficiencia respiratoria", "hemoptisis masiva", "desnutrición severa", "coinfección compleja"],
    nursing_priorities: ["Aislamiento respiratorio", "adherencia a tratamiento", "rastreo de contactos", "soporte nutricional"],
    diagnostic_support: ["Baciloscopia", "GeneXpert", "radiografía de tórax", "cultivo de esputo"],
  },
  {
    id: "meningitis-bacteriana",
    name: "Meningitis bacteriana",
    area: "Neurológico",
    urgency: "alta",
    summary: "Infección meníngea aguda con riesgo de sepsis y daño neurológico.",
    clinical_clues: ["Fiebre", "cefalea intensa", "rigidez de nuca", "fotofobia"],
    red_flags: ["Alteración de conciencia", "convulsiones", "choque séptico", "déficit focal"],
    nursing_priorities: ["Aislamiento y bioseguridad", "monitor neurológico frecuente", "administración antibiótica oportuna", "control hemodinámico"],
    diagnostic_support: ["Punción lumbar", "hemocultivos", "TAC previo si indicado", "PCR inflamatoria"],
  },
  {
    id: "encefalitis-viral",
    name: "Encefalitis viral",
    area: "Neurológico",
    urgency: "alta",
    summary: "Inflamación cerebral infecciosa con alteraciones cognitivas y conductuales agudas.",
    clinical_clues: ["Fiebre", "confusión", "cefalea", "cambios conductuales"],
    red_flags: ["Convulsiones repetidas", "coma", "hipertensión endocraneana", "inestabilidad autonómica"],
    nursing_priorities: ["Vigilancia neurológica continua", "control de vía aérea", "manejo de convulsiones", "soporte familiar"],
    diagnostic_support: ["LCR por PCR", "RM cerebral", "EEG", "panel infeccioso"],
  },
  {
    id: "hemorragia-subaracnoidea",
    name: "Hemorragia subaracnoidea",
    area: "Neurológico",
    urgency: "alta",
    summary: "Sangrado subaracnoideo agudo con riesgo de vasoespasmo y deterioro neurológico rápido.",
    clinical_clues: ["Cefalea en trueno", "rigidez cervical", "náusea", "fotofobia"],
    red_flags: ["Disminución del nivel de conciencia", "déficit focal", "convulsiones", "inestabilidad hemodinámica"],
    nursing_priorities: ["Control neurológico seriado", "manejo hemodinámico estricto", "prevención de vasoespasmo", "escalamiento neurocrítico"],
    diagnostic_support: ["TAC cerebral urgente", "angiotomografía", "LCR si TAC negativa", "monitorización intensiva"],
  },
  {
    id: "trauma-craneoencefalico",
    name: "Trauma craneoencefálico",
    area: "Neurológico",
    urgency: "alta",
    summary: "Lesión cerebral traumática con gravedad variable y riesgo de hipertensión endocraneana.",
    clinical_clues: ["Cefalea", "vómito", "amnesia", "somnolencia"],
    red_flags: ["Glasgow < 13", "anisocoria", "deterioro progresivo", "déficit focal"],
    nursing_priorities: ["ABC inicial", "inmovilización cervical", "vigilancia Glasgow", "prevención de lesión secundaria"],
    diagnostic_support: ["TAC cerebral", "monitor neurológico", "gasometría", "perfil de coagulación"],
  },
  {
    id: "delirium-agudo",
    name: "Delirium agudo",
    area: "Neurológico",
    urgency: "media",
    summary: "Síndrome confusional agudo secundario a causa médica subyacente.",
    clinical_clues: ["Fluctuación de atención", "desorientación", "agitación o hipoactividad", "inversión sueño-vigilia"],
    red_flags: ["Compromiso respiratorio", "sepsis no reconocida", "caídas recurrentes", "auto/heteroagresión"],
    nursing_priorities: ["Entorno seguro", "reorientación frecuente", "buscar causa precipitante", "control de fármacos de riesgo"],
    diagnostic_support: ["Laboratorios metabólicos", "tamizaje infeccioso", "ECG", "imagen según sospecha"],
  },
  {
    id: "hipoglucemia-severa",
    name: "Hipoglucemia severa",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descenso crítico de glucosa con riesgo neurológico y cardiovascular.",
    clinical_clues: ["Diaforesis", "temblor", "confusión", "somnolencia"],
    red_flags: ["Convulsiones", "coma", "arritmias", "déficit neurológico persistente"],
    nursing_priorities: ["Corrección inmediata de glucosa", "monitorizar conciencia", "evitar recurrencia", "educación sobre prevención"],
    diagnostic_support: ["Glucosa capilar seriada", "perfil metabólico", "función renal", "revisión de esquema terapéutico"],
  },
  {
    id: "estado-hiperosmolar",
    name: "Estado hiperosmolar hiperglucémico",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descompensación hiperglucémica grave con deshidratación y alteración del sensorio.",
    clinical_clues: ["Polidipsia", "debilidad", "deshidratación", "hiperglucemia extrema"],
    red_flags: ["Shock", "deterioro neurológico", "insuficiencia renal", "trombosis"],
    nursing_priorities: ["Reposición hídrica protocolizada", "monitor electrolitos", "insulina según guía", "vigilancia neurológica"],
    diagnostic_support: ["Osmolaridad plasmática", "electrolitos", "gasometría", "glucosa seriada"],
  },
  {
    id: "tormenta-tiroidea",
    name: "Tormenta tiroidea",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descompensación extrema del hipertiroidismo con riesgo vital.",
    clinical_clues: ["Fiebre alta", "taquicardia severa", "agitación", "diarrea"],
    red_flags: ["Arritmias", "insuficiencia cardiaca", "shock", "compromiso neurológico"],
    nursing_priorities: ["Control hemodinámico intensivo", "disminuir demanda metabólica", "administración terapéutica prescrita", "manejo térmico"],
    diagnostic_support: ["TSH/T4 libre", "ECG", "perfil hepático", "electrolitos"],
  },
  {
    id: "insuficiencia-suprarrenal-aguda",
    name: "Insuficiencia suprarrenal aguda",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Crisis adrenal con hipotensión y alteraciones electrolíticas severas.",
    clinical_clues: ["Debilidad intensa", "náusea/vómito", "hipotensión", "dolor abdominal"],
    red_flags: ["Shock refractario", "hiponatremia severa", "hiperkalemia", "alteración de conciencia"],
    nursing_priorities: ["Reposición de volumen", "monitorización hemodinámica", "administrar corticoides según orden", "vigilancia de electrolitos"],
    diagnostic_support: ["Cortisol basal", "electrolitos", "gasometría", "glucosa"],
  },
  {
    id: "hiponatremia-sintomatica",
    name: "Hiponatremia sintomática",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Trastorno hidroelectrolítico con riesgo neurológico por edema cerebral.",
    clinical_clues: ["Náusea", "cefalea", "confusión", "letargo"],
    red_flags: ["Convulsiones", "coma", "deterioro rápido", "insuficiencia respiratoria"],
    nursing_priorities: ["Corrección controlada de sodio", "vigilancia neurológica", "balance hídrico estricto", "detección de causa de base"],
    diagnostic_support: ["Sodio sérico seriado", "osmolaridad plasmática/urinaria", "función renal", "electrolitos completos"],
  },
  {
    id: "pielonefritis-aguda",
    name: "Pielonefritis aguda",
    area: "Renal",
    urgency: "media",
    summary: "Infección urinaria alta con compromiso sistémico variable.",
    clinical_clues: ["Fiebre", "dolor lumbar", "disuria", "escalofríos"],
    red_flags: ["Sepsis urinaria", "hipotensión", "vómito persistente", "deterioro renal agudo"],
    nursing_priorities: ["Hidratación y control térmico", "vigilancia de sepsis", "adherencia antibiótica", "control de dolor"],
    diagnostic_support: ["Urocultivo", "uroanálisis", "hemograma", "función renal"],
  },
  {
    id: "litiasis-renal-obstructiva",
    name: "Litiasis renal obstructiva",
    area: "Renal",
    urgency: "media",
    summary: "Obstrucción urinaria por cálculo con dolor intenso y riesgo infeccioso.",
    clinical_clues: ["Cólico renal", "hematuria", "náusea", "inquietud psicomotora"],
    red_flags: ["Anuria", "fiebre alta", "sepsis urinaria", "dolor refractario"],
    nursing_priorities: ["Control del dolor", "monitor de diuresis", "vigilancia infecciosa", "preparar procedimientos de desobstrucción"],
    diagnostic_support: ["TAC simple renal", "ecografía renal", "uroanálisis", "creatinina sérica"],
  },
  {
    id: "glomerulonefritis-aguda",
    name: "Glomerulonefritis aguda",
    area: "Renal",
    urgency: "media",
    summary: "Inflamación glomerular con edema, hipertensión y deterioro de función renal.",
    clinical_clues: ["Edema periorbitario", "hematuria", "hipertensión", "oliguria"],
    red_flags: ["Hipertensión severa", "sobrecarga hídrica", "deterioro renal progresivo", "encefalopatía hipertensiva"],
    nursing_priorities: ["Balance hídrico", "control de presión arterial", "vigilancia renal", "educación en restricción salina"],
    diagnostic_support: ["EGO y proteinuria", "complemento sérico", "función renal", "ecografía renal"],
  },
  {
    id: "hiperpotasemia-grave",
    name: "Hiperpotasemia grave",
    area: "Renal",
    urgency: "alta",
    summary: "Elevación crítica de potasio con riesgo de arritmias fatales.",
    clinical_clues: ["Debilidad muscular", "parestesias", "náusea", "bradicardia"],
    red_flags: ["Arritmias en ECG", "bloqueo AV", "paro cardíaco", "hipotensión"],
    nursing_priorities: ["Monitor cardíaco continuo", "tratamiento corrector inmediato", "control seriado de potasio", "revisión de fármacos causales"],
    diagnostic_support: ["Electrolitos urgentes", "ECG", "función renal", "gasometría"],
  },
  {
    id: "celulitis-complicada",
    name: "Celulitis complicada",
    area: "Infeccioso",
    urgency: "media",
    summary: "Infección de piel y tejidos blandos con riesgo de extensión sistémica.",
    clinical_clues: ["Eritema", "dolor local", "calor", "edema"],
    red_flags: ["Fiebre alta persistente", "necrosis", "hipotensión", "rápida progresión"],
    nursing_priorities: ["Evaluar extensión de lesión", "control de dolor", "antibiótico oportuno", "educación sobre cuidados locales"],
    diagnostic_support: ["Hemograma", "PCR", "cultivo de exudado", "ecografía de partes blandas"],
  },
  {
    id: "neutropenia-febril",
    name: "Neutropenia febril",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Emergencia oncohematológica por infección potencial en paciente neutropénico.",
    clinical_clues: ["Fiebre >38°C", "malestar general", "escalofríos", "lesiones mucosas"],
    red_flags: ["Hipotensión", "sepsis", "deterioro respiratorio", "foco infeccioso invasivo"],
    nursing_priorities: ["Aislamiento protector", "hemocultivos tempranos", "antibiótico empírico rápido", "monitorización estrecha"],
    diagnostic_support: ["Hemograma urgente", "hemocultivos", "lactato", "radiografía de tórax"],
  },
  {
    id: "vih-avanzado",
    name: "VIH avanzado",
    area: "Infeccioso",
    urgency: "media",
    summary: "Inmunosupresión severa con riesgo de infecciones oportunistas y deterioro funcional.",
    clinical_clues: ["Pérdida de peso", "fiebre prolongada", "candidiasis recurrente", "debilidad"],
    red_flags: ["Infección oportunista grave", "insuficiencia respiratoria", "alteración neurológica", "sepsis"],
    nursing_priorities: ["Adherencia terapéutica", "tamizaje de oportunistas", "soporte nutricional", "acompañamiento psicosocial"],
    diagnostic_support: ["Carga viral", "CD4", "hemograma", "panel infeccioso dirigido"],
  },
  {
    id: "infeccion-intraabdominal",
    name: "Infección intraabdominal complicada",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Proceso infeccioso abdominal con riesgo de sepsis y peritonitis.",
    clinical_clues: ["Dolor abdominal difuso", "fiebre", "náusea/vómito", "taquicardia"],
    red_flags: ["Hipotensión", "defensa involuntaria", "lactato elevado", "oliguria"],
    nursing_priorities: ["Resucitación inicial", "vigilancia de sepsis", "control de dolor", "preparar intervención quirúrgica si indicada"],
    diagnostic_support: ["TAC abdominal", "hemocultivos", "lactato", "hemograma y PCR"],
  },
  {
    id: "fiebre-origen-desconocido",
    name: "Fiebre de origen desconocido",
    area: "Infeccioso",
    urgency: "media",
    summary: "Síndrome febril prolongado sin etiología inicial clara.",
    clinical_clues: ["Fiebre persistente", "astenia", "sudoración nocturna", "pérdida de peso"],
    red_flags: ["Inestabilidad hemodinámica", "deterioro respiratorio", "compromiso neurológico", "inmunosupresión severa"],
    nursing_priorities: ["Monitor térmico y hemodinámico", "registro clínico dirigido", "apoyo diagnóstico escalonado", "educación sobre signos de alarma"],
    diagnostic_support: ["Hemocultivos seriados", "imagen dirigida", "perfil inflamatorio", "estudios microbiológicos"],
  },
  {
    id: "pancreatitis-aguda",
    name: "Pancreatitis aguda",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Inflamación aguda pancreática con riesgo de falla orgánica en formas severas.",
    clinical_clues: ["Dolor epigástrico intenso", "náusea/vómito", "distensión abdominal", "taquicardia"],
    red_flags: ["Hipotensión", "hipoxemia", "oliguria", "deterioro metabólico"],
    nursing_priorities: ["Reposición hídrica", "control de dolor", "monitor de complicaciones", "soporte nutricional progresivo"],
    diagnostic_support: ["Lipasa sérica", "TAC abdominal", "hemoconcentración", "perfil metabólico"],
  },
  {
    id: "colecistitis-aguda",
    name: "Colecistitis aguda",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Inflamación vesicular aguda, usualmente litiásica, con dolor y fiebre.",
    clinical_clues: ["Dolor en hipocondrio derecho", "fiebre", "náusea", "Murphy positivo"],
    red_flags: ["Sepsis biliar", "perforación", "ictericia progresiva", "dolor refractario"],
    nursing_priorities: ["Ayuno y analgesia", "control térmico", "vigilancia de sepsis", "preparación para resolución quirúrgica"],
    diagnostic_support: ["Ecografía hepatobiliar", "hemograma", "perfil hepático", "PCR"],
  },
  {
    id: "hemorragia-digestiva-alta",
    name: "Hemorragia digestiva alta",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Sangrado de tracto digestivo superior con riesgo de choque hipovolémico.",
    clinical_clues: ["Hematemesis", "melenas", "palidez", "taquicardia"],
    red_flags: ["Hipotensión", "síncope", "sangrado activo masivo", "alteración de conciencia"],
    nursing_priorities: ["ABC y vía venosa", "cuantificar sangrado", "monitor hemodinámico", "preparar endoscopia urgente"],
    diagnostic_support: ["Hemograma seriado", "coagulación", "grupo y cruce", "endoscopia digestiva alta"],
  },
  {
    id: "obstruccion-intestinal",
    name: "Obstrucción intestinal",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Interrupción del tránsito intestinal con riesgo de isquemia y perforación.",
    clinical_clues: ["Dolor cólico", "distensión", "vómito", "ausencia de evacuaciones"],
    red_flags: ["Peritonitis", "fiebre alta", "hipotensión", "acidosis metabólica"],
    nursing_priorities: ["Descompresión si indicada", "balance hídrico", "control de dolor", "vigilancia de sepsis"],
    diagnostic_support: ["Radiografía abdominal", "TAC", "electrolitos", "lactato"],
  },
  {
    id: "cirrosis-descompensada",
    name: "Cirrosis descompensada",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Enfermedad hepática avanzada con ascitis, encefalopatía y riesgo hemorrágico.",
    clinical_clues: ["Ascitis", "ictericia", "edema", "fatiga intensa"],
    red_flags: ["Encefalopatía grave", "hemorragia variceal", "peritonitis bacteriana", "insuficiencia renal"],
    nursing_priorities: ["Control de balance", "vigilancia neurológica", "prevención de sangrado", "educación en adherencia"],
    diagnostic_support: ["Perfil hepático", "coagulación", "paracentesis diagnóstica", "función renal"],
  },
  {
    id: "embarazo-ectopico",
    name: "Embarazo ectópico",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Implantación extrauterina con riesgo de ruptura y hemorragia interna.",
    clinical_clues: ["Dolor pélvico", "amenorrea", "sangrado vaginal", "mareo"],
    red_flags: ["Inestabilidad hemodinámica", "dolor abdominal intenso", "síncope", "signos de choque"],
    nursing_priorities: ["Monitor hemodinámico", "vía venosa y fluidos", "preparar intervención urgente", "apoyo emocional"],
    diagnostic_support: ["Beta-hCG seriada", "ecografía transvaginal", "hemograma", "grupo y factor"],
  },
  {
    id: "amenaza-parto-pretermino",
    name: "Amenaza de parto pretérmino",
    area: "Gineco-obstétrico",
    urgency: "media",
    summary: "Actividad uterina y cambios cervicales antes de término con riesgo neonatal.",
    clinical_clues: ["Contracciones regulares", "dolor lumbar", "presión pélvica", "cambios cervicales"],
    red_flags: ["Rotura de membranas", "sangrado moderado-alto", "fiebre materna", "sufrimiento fetal"],
    nursing_priorities: ["Monitor materno-fetal", "reposo relativo según indicación", "educación de alarma", "coordinación obstétrica"],
    diagnostic_support: ["Tococardiografía", "ecografía cervical", "laboratorio infeccioso", "evaluación obstétrica seriada"],
  },
  {
    id: "placenta-previa",
    name: "Placenta previa con sangrado",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Implantación placentaria baja con hemorragia obstétrica potencialmente severa.",
    clinical_clues: ["Sangrado rojo rutilante", "ausencia de dolor intenso", "palidez", "taquicardia"],
    red_flags: ["Sangrado abundante", "hipotensión", "compromiso fetal", "choque"],
    nursing_priorities: ["Cuantificar sangrado", "monitorización fetal", "preparar hemoderivados", "escalamiento obstétrico"],
    diagnostic_support: ["Ecografía obstétrica", "hemograma", "coagulación", "grupo y reserva"],
  },
  {
    id: "infeccion-puerperal",
    name: "Infección puerperal",
    area: "Gineco-obstétrico",
    urgency: "media",
    summary: "Proceso infeccioso posparto con riesgo de sepsis materna.",
    clinical_clues: ["Fiebre posparto", "dolor pélvico", "loquios fétidos", "malestar general"],
    red_flags: ["Hipotensión", "taquicardia persistente", "dolor abdominal severo", "sepsis"],
    nursing_priorities: ["Detección temprana de sepsis", "manejo antibiótico", "higiene y cuidados perineales", "educación para seguimiento"],
    diagnostic_support: ["Hemograma", "cultivos", "PCR", "ecografía pélvica"],
  },
  {
    id: "aborto-incompleto",
    name: "Aborto incompleto complicado",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Retención de tejido gestacional con sangrado y riesgo infeccioso.",
    clinical_clues: ["Sangrado vaginal", "dolor tipo cólico", "expulsión parcial de tejido", "debilidad"],
    red_flags: ["Hemorragia activa", "fiebre", "hipotensión", "signos de sepsis"],
    nursing_priorities: ["Control hemodinámico", "manejo del dolor", "preparar evacuación uterina", "acompañamiento emocional"],
    diagnostic_support: ["Ecografía transvaginal", "hemograma", "Beta-hCG", "grupo y factor Rh"],
  },
  {
    id: "crup",
    name: "Crup (laringotraqueítis)",
    area: "Pediatría",
    urgency: "media",
    summary: "Inflamación de vía aérea superior pediátrica con tos perruna y estridor.",
    clinical_clues: ["Tos perruna", "estridor inspiratorio", "disfonía", "agitación nocturna"],
    red_flags: ["Estridor en reposo", "tirajes severos", "cianosis", "fatiga respiratoria"],
    nursing_priorities: ["Mantener calma del niño", "oxigenación y nebulización según orden", "vigilar trabajo respiratorio", "educar cuidadores"],
    diagnostic_support: ["Valoración clínica", "oximetría", "escala de severidad", "imagen solo si duda diagnóstica"],
  },
  {
    id: "neumonia-pediatrica",
    name: "Neumonía pediátrica",
    area: "Pediatría",
    urgency: "media",
    summary: "Infección respiratoria baja en niños con riesgo de hipoxemia y sepsis.",
    clinical_clues: ["Fiebre", "tos", "taquipnea", "tirajes"],
    red_flags: ["SatO2 baja", "apneas", "deshidratación", "compromiso del estado general"],
    nursing_priorities: ["Soporte respiratorio", "hidratación", "antibiótico según indicación", "educación familiar"],
    diagnostic_support: ["Radiografía de tórax", "oximetría", "hemograma", "PCR"],
  },
  {
    id: "deshidratacion-aguda-pediatrica",
    name: "Deshidratación aguda pediátrica",
    area: "Pediatría",
    urgency: "media",
    summary: "Déficit hídrico en niño con riesgo de choque hipovolémico.",
    clinical_clues: ["Mucosas secas", "llanto sin lágrimas", "taquicardia", "llenado capilar lento"],
    red_flags: ["Letargia", "anuria", "hipotensión", "alteración de conciencia"],
    nursing_priorities: ["Reposición hídrica según plan", "monitor de diuresis", "control de signos vitales", "educación en hidratación oral"],
    diagnostic_support: ["Electrolitos", "gases venosos", "glucosa", "evaluación clínica seriada"],
  },
  {
    id: "convulsion-febril-compleja",
    name: "Convulsión febril compleja",
    area: "Pediatría",
    urgency: "alta",
    summary: "Crisis convulsiva febril con características atípicas que requieren estudio ampliado.",
    clinical_clues: ["Convulsión >15 min", "focalidad", "recurrencia en 24h", "fiebre"],
    red_flags: ["Estado postictal prolongado", "meningismo", "deterioro neurológico", "compromiso respiratorio"],
    nursing_priorities: ["Asegurar vía aérea", "control de temperatura", "vigilancia neurológica", "contención familiar"],
    diagnostic_support: ["Glucosa capilar", "electrolitos", "evaluación neurológica", "punción lumbar según criterio"],
  },
  {
    id: "sepsis-neonatal",
    name: "Sepsis neonatal",
    area: "Pediatría",
    urgency: "alta",
    summary: "Infección sistémica neonatal con alta morbimortalidad sin tratamiento precoz.",
    clinical_clues: ["Letargia", "rechazo al alimento", "inestabilidad térmica", "dificultad respiratoria"],
    red_flags: ["Apneas", "choque", "hipoglucemia persistente", "convulsiones"],
    nursing_priorities: ["Monitor cardiorrespiratorio", "acceso vascular seguro", "antibiótico temprano", "soporte térmico"],
    diagnostic_support: ["Hemocultivo", "hemograma", "PCR/procalcitonina", "gases y glucosa"],
  },
  {
    id: "anafilaxia",
    name: "Anafilaxia",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Reacción de hipersensibilidad sistémica grave con riesgo de obstrucción aérea y choque.",
    clinical_clues: ["Urticaria", "edema facial", "sibilancias", "hipotensión"],
    red_flags: ["Compromiso de vía aérea", "estridor", "choque", "deterioro rápido"],
    nursing_priorities: ["Adrenalina inmediata según protocolo", "ABC y oxígeno", "monitorización continua", "preparar manejo avanzado de vía aérea"],
    diagnostic_support: ["Diagnóstico clínico inmediato", "monitor hemodinámico", "gasometría según gravedad", "triptasa si disponible"],
  },
  {
    id: "paro-cardiorrespiratorio",
    name: "Paro cardiorrespiratorio",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Cese de actividad circulatoria y respiratoria que requiere RCP inmediata.",
    clinical_clues: ["Ausencia de pulso", "inconsciencia", "apnea o respiración agónica", "cianosis"],
    red_flags: ["Ritmo desfibrilable", "no respuesta a RCP inicial", "hipoxia grave", "causas reversibles no corregidas"],
    nursing_priorities: ["RCP de alta calidad", "desfibrilación oportuna", "manejo de vía aérea", "coordinación del equipo de reanimación"],
    diagnostic_support: ["Monitor/ECG", "gasometría", "electrolitos", "evaluación de H y T"],
  },
  {
    id: "sangrado-masivo",
    name: "Sangrado masivo",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Hemorragia aguda severa con riesgo de choque y coagulopatía.",
    clinical_clues: ["Hipotensión", "taquicardia", "palidez", "sangrado activo"],
    red_flags: ["Choque refractario", "coagulopatía", "acidosis", "hipotermia"],
    nursing_priorities: ["Control de foco hemorrágico", "activación de protocolo de transfusión", "monitor hemodinámico", "calentamiento activo"],
    diagnostic_support: ["Hemograma seriado", "coagulación", "lactato", "grupo y reserva sanguínea"],
  },
  {
    id: "intoxicacion-aguda",
    name: "Intoxicación aguda",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Exposición tóxica con compromiso neurológico, respiratorio o hemodinámico.",
    clinical_clues: ["Alteración de conciencia", "náusea/vómito", "cambios pupilares", "inestabilidad autonómica"],
    red_flags: ["Depresión respiratoria", "convulsiones", "arritmias", "coma"],
    nursing_priorities: ["ABC y soporte vital", "descontaminación según protocolo", "identificar tóxico probable", "consulta toxicológica"],
    diagnostic_support: ["Gases arteriales", "toxicología dirigida", "electrolitos", "ECG"],
  },
  {
    id: "estatus-asmatico",
    name: "Estatus asmático",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Exacerbación asmática grave refractaria al tratamiento inicial.",
    clinical_clues: ["Disnea intensa", "sibilancias difusas", "taquicardia", "dificultad para hablar"],
    red_flags: ["Silencio auscultatorio", "fatiga respiratoria", "hipoxemia persistente", "hipercapnia"],
    nursing_priorities: ["Broncodilatación intensiva", "oxígeno escalonado", "vigilancia ventilatoria", "preparar soporte avanzado"],
    diagnostic_support: ["Oximetría continua", "gasometría", "PEF seriado", "radiografía según evolución"],
  },
  {
    id: "quemaduras-graves",
    name: "Quemaduras graves",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Lesión térmica extensa con riesgo de choque, infección y falla orgánica.",
    clinical_clues: ["Dolor intenso", "ampollas/escaras", "pérdida de líquidos", "taquicardia"],
    red_flags: ["Compromiso de vía aérea", "hipotensión", "superficie corporal extensa", "inhalación de humo"],
    nursing_priorities: ["ABC inicial", "reposición hídrica por fórmula", "analgesia", "prevención de infección y pérdida térmica"],
    diagnostic_support: ["Cálculo de SCQ", "gasometría", "electrolitos", "carboxihemoglobina si humo"],
  },
];

export const MEDICAL_PATHOLOGY_LIBRARY: MedicalPathology[] = [];

const BASE_MEDICAL_PATHOLOGY_LIBRARY: MedicalPathology[] = [
  {
    id: "hta",
    name: "Hipertensión arterial",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Elevación sostenida de presión arterial con riesgo de daño de órgano blanco.",
    clinical_clues: ["Cefalea ocasional", "mareo", "lecturas elevadas repetidas", "asintomática en fases iniciales"],
    red_flags: ["Crisis hipertensiva", "dolor torácico", "déficit neurológico agudo", "disnea súbita"],
    nursing_priorities: ["Toma correcta de PA", "adherencia terapéutica", "educación en estilo de vida", "seguimiento periódico"],
    diagnostic_support: ["Monitoreo ambulatorio de PA", "creatinina y electrolitos", "ECG", "fondo de ojo si aplica"],
  },
  {
    id: "iac",
    name: "Insuficiencia cardiaca",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Síndrome de falla de bomba con congestión y deterioro de perfusión.",
    clinical_clues: ["Disnea de esfuerzo", "edema periférico", "ortopnea", "fatiga"],
    red_flags: ["Edema agudo de pulmón", "hipotensión", "hipoxemia refractaria", "alteración del estado mental"],
    nursing_priorities: ["Balance hídrico estricto", "control de peso", "monitorización respiratoria", "educación sobre restricción de sodio"],
    diagnostic_support: ["BNP/NT-proBNP", "radiografía de tórax", "ecocardiograma", "función renal"],
  },
  {
    id: "sca",
    name: "Síndrome coronario agudo",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Isquemia miocárdica aguda por obstrucción coronaria.",
    clinical_clues: ["Dolor torácico opresivo", "diaforesis", "náuseas", "irradiación a brazo o mandíbula"],
    red_flags: ["Inestabilidad hemodinámica", "arritmias malignas", "dolor persistente >20 min", "síncope"],
    nursing_priorities: ["Activar protocolo de dolor torácico", "monitor cardíaco", "oxigenación según necesidad", "preparar para reperfusión"],
    diagnostic_support: ["ECG seriado", "troponinas", "radiografía de tórax", "estratificación de riesgo"],
  },
  {
    id: "asma",
    name: "Asma bronquial",
    area: "Respiratorio",
    urgency: "media",
    summary: "Inflamación crónica de vía aérea con hiperreactividad y obstrucción variable.",
    clinical_clues: ["Sibilancias", "tos nocturna", "disnea episódica", "síntomas con desencadenantes"],
    red_flags: ["Silencio auscultatorio", "uso intenso de músculos accesorios", "cianosis", "alteración de conciencia"],
    nursing_priorities: ["Evaluar patrón respiratorio", "educación en inhaladores", "identificar desencadenantes", "plan de acción escrito"],
    diagnostic_support: ["Espirometría", "PEF seriado", "oximetría", "gasometría en crisis severa"],
  },
  {
    id: "epoc",
    name: "EPOC",
    area: "Respiratorio",
    urgency: "media",
    summary: "Limitación crónica al flujo aéreo, generalmente progresiva y asociada a exposición a humo.",
    clinical_clues: ["Tos crónica", "expectoración", "disnea progresiva", "intolerancia al esfuerzo"],
    red_flags: ["Exacerbación con hipercapnia", "somnolencia", "cianosis", "falla respiratoria"],
    nursing_priorities: ["Educación para dejar tabaco", "técnicas respiratorias", "uso correcto de broncodilatadores", "vacunación"],
    diagnostic_support: ["Espirometría posbroncodilatador", "radiografía de tórax", "gasometría", "hemograma"],
  },
  {
    id: "neumonia",
    name: "Neumonía adquirida en la comunidad",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Infección del parénquima pulmonar con compromiso respiratorio variable.",
    clinical_clues: ["Fiebre", "tos productiva", "dolor pleurítico", "taquipnea"],
    red_flags: ["SatO2 < 90%", "sepsis", "hipotensión", "confusión aguda"],
    nursing_priorities: ["Evaluar oxigenación", "control térmico e hidratación", "adherencia antibiótica", "vigilancia de signos de sepsis"],
    diagnostic_support: ["Radiografía de tórax", "hemograma y PCR", "oximetría", "hemocultivos según gravedad"],
  },
  {
    id: "acv",
    name: "Accidente cerebrovascular",
    area: "Neurológico",
    urgency: "alta",
    summary: "Déficit neurológico focal súbito por causa vascular.",
    clinical_clues: ["Hemiparesia", "disartria", "asimetría facial", "alteración súbita del lenguaje"],
    red_flags: ["Inicio < 4.5 h", "deterioro rápido del nivel de conciencia", "cefalea intensa súbita", "convulsión inicial"],
    nursing_priorities: ["Activar código ictus", "control de vía aérea y glucemia", "prevención de broncoaspiración", "registro de hora de inicio"],
    diagnostic_support: ["TAC de cráneo urgente", "glucosa capilar", "ECG", "laboratorios básicos"],
  },
  {
    id: "epilepsia",
    name: "Epilepsia",
    area: "Neurológico",
    urgency: "media",
    summary: "Predisposición persistente a crisis epilépticas recurrentes.",
    clinical_clues: ["Crisis motoras o focales", "periodo postictal", "antecedentes neurológicos"],
    red_flags: ["Estatus epiléptico", "trauma asociado grave", "déficit neurológico persistente", "primera crisis con fiebre alta en adulto"],
    nursing_priorities: ["Seguridad durante crisis", "adherencia a antiepilépticos", "educación familiar", "registro de características de crisis"],
    diagnostic_support: ["EEG", "neuroimagen según caso", "niveles de fármacos", "perfil metabólico"],
  },
  {
    id: "dm2",
    name: "Diabetes mellitus tipo 2",
    area: "Endocrino-metabólico",
    urgency: "media",
    summary: "Trastorno metabólico con hiperglucemia crónica por resistencia a insulina y déficit relativo.",
    clinical_clues: ["Poliuria", "polidipsia", "fatiga", "infecciones recurrentes"],
    red_flags: ["Cetoacidosis", "estado hiperosmolar", "hipoglucemia severa", "pie diabético infectado"],
    nursing_priorities: ["Educación en autocontrol glucémico", "plan alimentario", "adherencia farmacológica", "cuidado de pies"],
    diagnostic_support: ["Glucosa en ayunas", "HbA1c", "perfil lipídico", "función renal y microalbuminuria"],
  },
  {
    id: "hipotiroidismo",
    name: "Hipotiroidismo",
    area: "Endocrino-metabólico",
    urgency: "baja",
    summary: "Déficit de hormonas tiroideas con enlentecimiento metabólico.",
    clinical_clues: ["Fatiga", "aumento de peso", "piel seca", "estreñimiento"],
    red_flags: ["Coma mixedematoso", "bradicardia severa", "hipotermia", "somnolencia progresiva"],
    nursing_priorities: ["Educación sobre toma de levotiroxina", "seguimiento de síntomas", "adherencia a controles", "prevención de interacciones farmacológicas"],
    diagnostic_support: ["TSH", "T4 libre", "anticuerpos antitiroideos", "perfil lipídico"],
  },
  {
    id: "erc",
    name: "Enfermedad renal crónica",
    area: "Renal",
    urgency: "media",
    summary: "Disminución progresiva de función renal y/o daño renal persistente.",
    clinical_clues: ["Edema", "fatiga", "anemia", "alteraciones hidroelectrolíticas"],
    red_flags: ["Hiperkalemia", "sobrecarga hídrica severa", "acidosis metabólica", "síntomas urémicos"],
    nursing_priorities: ["Balance hídrico", "control de PA", "educación nutricional renal", "adherencia a nefroprotección"],
    diagnostic_support: ["TFG estimada", "creatinina", "uroanálisis y albuminuria", "electrolitos"],
  },
  {
    id: "ira",
    name: "Lesión renal aguda",
    area: "Renal",
    urgency: "alta",
    summary: "Deterioro súbito de la función renal con retención de productos nitrogenados.",
    clinical_clues: ["Oliguria", "aumento rápido de creatinina", "edema", "náusea"],
    red_flags: ["Anuria", "hiperkalemia severa", "edema pulmonar", "encefalopatía urémica"],
    nursing_priorities: ["Monitor diuresis horaria", "detectar nefrotóxicos", "control de volemia", "escalamiento temprano"],
    diagnostic_support: ["Creatinina seriada", "electrolitos", "uroanálisis", "ecografía renal"],
  },
  {
    id: "sepsis",
    name: "Sepsis",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Disfunción orgánica potencialmente mortal secundaria a respuesta desregulada a infección.",
    clinical_clues: ["Fiebre o hipotermia", "taquicardia", "taquipnea", "hipotensión"],
    red_flags: ["Lactato elevado", "oliguria", "alteración de conciencia", "shock"],
    nursing_priorities: ["Reconocimiento temprano", "protocolo primera hora", "control hemodinámico", "antibiótico oportuno"],
    diagnostic_support: ["Lactato", "hemocultivos", "hemograma", "función renal/hepática"],
  },
  {
    id: "itu",
    name: "Infección urinaria",
    area: "Infeccioso",
    urgency: "baja",
    summary: "Infección del tracto urinario inferior o superior según localización.",
    clinical_clues: ["Disuria", "polaquiuria", "urgencia miccional", "dolor suprapúbico"],
    red_flags: ["Fiebre alta con dolor lumbar", "sepsis urinaria", "embarazo con síntomas", "vómito persistente"],
    nursing_priorities: ["Educación en hidratación e higiene", "adherencia al antibiótico", "vigilancia de progresión a pielonefritis", "control de síntomas"],
    diagnostic_support: ["Uroanálisis", "urocultivo", "hemograma si fiebre", "ecografía si complicación"],
  },
  {
    id: "gastroenteritis",
    name: "Gastroenteritis aguda",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Proceso inflamatorio intestinal agudo con diarrea y posible deshidratación.",
    clinical_clues: ["Diarrea", "náusea", "vómito", "dolor abdominal tipo cólico"],
    red_flags: ["Deshidratación severa", "sangrado digestivo", "fiebre persistente alta", "alteración del estado mental"],
    nursing_priorities: ["Reposición hídrica", "balance hídrico", "vigilancia de signos de choque", "educación alimentaria"],
    diagnostic_support: ["Electrolitos", "coproanálisis según contexto", "hemograma", "función renal"],
  },
  {
    id: "apendicitis",
    name: "Apendicitis aguda",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Inflamación aguda del apéndice con riesgo de perforación.",
    clinical_clues: ["Dolor migratorio a fosa iliaca derecha", "náusea", "vómito", "fiebre"],
    red_flags: ["Peritonismo", "dolor generalizado", "inestabilidad hemodinámica", "sepsis abdominal"],
    nursing_priorities: ["Ayuno y preparación prequirúrgica", "control del dolor", "vigilancia de signos peritoneales", "educación perioperatoria"],
    diagnostic_support: ["Hemograma", "PCR", "ecografía", "TAC según caso"],
  },
  {
    id: "preeclampsia",
    name: "Preeclampsia",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Hipertensión gestacional con daño orgánico materno y riesgo fetal.",
    clinical_clues: ["PA elevada en embarazo", "cefalea", "fosfenos", "edema"],
    red_flags: ["Convulsiones", "dolor epigástrico intenso", "oliguria", "compromiso fetal"],
    nursing_priorities: ["Monitor materno-fetal", "control de PA", "detección de signos de eclampsia", "educación sobre alarma"],
    diagnostic_support: ["Proteinuria", "función hepática y renal", "plaquetas", "ecografía obstétrica"],
  },
  {
    id: "hemorragia-posparto",
    name: "Hemorragia posparto",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Pérdida sanguínea excesiva tras parto con riesgo de choque hipovolémico.",
    clinical_clues: ["Sangrado abundante", "taquicardia", "hipotensión", "palidez"],
    red_flags: ["Choque", "coagulopatía", "alteración del estado mental", "persistencia pese a medidas iniciales"],
    nursing_priorities: ["Activar protocolo obstétrico", "canalización y fluidos", "cuantificar sangrado", "apoyo emocional a paciente/familia"],
    diagnostic_support: ["Hemograma", "coagulación", "grupo y reserva de sangre", "ecografía si sospecha retención"],
  },
  {
    id: "bronquiolitis",
    name: "Bronquiolitis",
    area: "Pediatría",
    urgency: "media",
    summary: "Infección respiratoria baja en lactantes con obstrucción de vía aérea pequeña.",
    clinical_clues: ["Tos", "sibilancias", "taquipnea", "dificultad alimentaria"],
    red_flags: ["Apneas", "cianosis", "deshidratación", "hipoxemia persistente"],
    nursing_priorities: ["Soporte respiratorio", "higiene nasal", "hidratación", "educación a cuidadores"],
    diagnostic_support: ["Valoración clínica", "oximetría", "gasometría si grave", "imagen solo en casos seleccionados"],
  },
  {
    id: "dengue",
    name: "Dengue",
    area: "Infeccioso",
    urgency: "media",
    summary: "Arbovirosis con espectro de fiebre no complicada a formas graves con fuga capilar.",
    clinical_clues: ["Fiebre alta", "mialgias", "cefalea retroocular", "rash"],
    red_flags: ["Dolor abdominal intenso", "sangrado", "letargo", "hipotensión"],
    nursing_priorities: ["Hidratación controlada", "vigilancia de signos de alarma", "educación sobre retorno", "control de temperatura"],
    diagnostic_support: ["Hemograma seriado", "hematocrito", "plaquetas", "pruebas antigénicas/serológicas"],
  },
  {
    id: "shock-septico",
    name: "Shock séptico",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Forma grave de sepsis con hipotensión persistente y alteración de perfusión tisular.",
    clinical_clues: ["Hipotensión refractaria", "lactato elevado", "piel moteada", "oliguria"],
    red_flags: ["Falla multiorgánica", "hipoxemia grave", "deterioro neurológico", "acidosis progresiva"],
    nursing_priorities: ["Monitorización intensiva", "vasopresores según indicación", "control de perfusión", "prevención de lesiones por presión"],
    diagnostic_support: ["Lactato seriado", "gasometría", "hemocultivos", "perfil orgánico completo"],
  },
  {
    id: "politrauma",
    name: "Politrauma",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Compromiso multisistémico por trauma de alta energía.",
    clinical_clues: ["Lesiones múltiples", "dolor severo", "inestabilidad hemodinámica", "alteración neurológica"],
    red_flags: ["Compromiso de vía aérea", "hemorragia activa", "choque", "déficit neurológico progresivo"],
    nursing_priorities: ["Enfoque ABCDE", "control de hemorragia", "inmovilización y seguridad", "coordinación de equipo"],
    diagnostic_support: ["FAST", "TAC trauma", "hemograma/coagulación", "lactato"],
  },
  {
    id: "cetoacidosis",
    name: "Cetoacidosis diabética",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Descompensación metabólica aguda por déficit de insulina con cetosis y acidosis.",
    clinical_clues: ["Poliuria", "polidipsia", "dolor abdominal", "respiración de Kussmaul"],
    red_flags: ["Alteración de conciencia", "hipotensión", "hiperkalemia", "acidosis severa"],
    nursing_priorities: ["Hidratación guiada", "insulina protocolizada", "monitor electrolitos", "vigilancia neurológica"],
    diagnostic_support: ["Gasometría", "cetonas", "electrolitos", "glucosa seriada"],
  },
];

MEDICAL_PATHOLOGY_LIBRARY.push(
  ...BASE_MEDICAL_PATHOLOGY_LIBRARY,
  ...EXTRA_MEDICAL_PATHOLOGY_LIBRARY
);
