export type MedicalArea =
  | "Cardiovascular"
  | "Respiratorio"
  | "Neurológico"
  | "Endocrino-metabólico"
  | "Renal"
  | "Infeccioso"
  | "Gastrointestinal"
  | "Gineco-obstétrico"
  | "Pediatría"
  | "Urgencias y críticos";

export type MedicalUrgency = "baja" | "media" | "alta";

export type MedicalPathology = {
  id: string;
  name: string;
  area: MedicalArea;
  urgency: MedicalUrgency;
  summary: string;
  clinical_clues: string[];
  red_flags: string[];
  nursing_priorities: string[];
  diagnostic_support: string[];
};

export const MEDICAL_AREAS: MedicalArea[] = [
  "Cardiovascular",
  "Respiratorio",
  "Neurológico",
  "Endocrino-metabólico",
  "Renal",
  "Infeccioso",
  "Gastrointestinal",
  "Gineco-obstétrico",
  "Pediatría",
  "Urgencias y críticos",
];

export const MEDICAL_PATHOLOGY_LIBRARY: MedicalPathology[] = [
  {
    id: "hta",
    name: "Hipertensión arterial",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Elevación sostenida de presión arterial con riesgo de daño de órgano blanco.",
    clinical_clues: ["Cefalea ocasional", "mareo", "lecturas elevadas repetidas", "asintomática en fases iniciales"],
    red_flags: ["Crisis hipertensiva", "dolor torácico", "déficit neurológico agudo", "disnea súbita"],
    nursing_priorities: ["Toma correcta de PA", "adherencia terapéutica", "educación en estilo de vida", "seguimiento periódico"],
    diagnostic_support: ["Monitoreo ambulatorio de PA", "creatinina y electrolitos", "ECG", "fondo de ojo si aplica"],
  },
  {
    id: "iac",
    name: "Insuficiencia cardiaca",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Síndrome de falla de bomba con congestión y deterioro de perfusión.",
    clinical_clues: ["Disnea de esfuerzo", "edema periférico", "ortopnea", "fatiga"],
    red_flags: ["Edema agudo de pulmón", "hipotensión", "hipoxemia refractaria", "alteración del estado mental"],
    nursing_priorities: ["Balance hídrico estricto", "control de peso", "monitorización respiratoria", "educación sobre restricción de sodio"],
    diagnostic_support: ["BNP/NT-proBNP", "radiografía de tórax", "ecocardiograma", "función renal"],
  },
  {
    id: "sca",
    name: "Síndrome coronario agudo",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Isquemia miocárdica aguda por obstrucción coronaria.",
    clinical_clues: ["Dolor torácico opresivo", "diaforesis", "náuseas", "irradiación a brazo o mandíbula"],
    red_flags: ["Inestabilidad hemodinámica", "arritmias malignas", "dolor persistente >20 min", "síncope"],
    nursing_priorities: ["Activar protocolo de dolor torácico", "monitor cardíaco", "oxigenación según necesidad", "preparar para reperfusión"],
    diagnostic_support: ["ECG seriado", "troponinas", "radiografía de tórax", "estratificación de riesgo"],
  },
  {
    id: "asma",
    name: "Asma bronquial",
    area: "Respiratorio",
    urgency: "media",
    summary: "Inflamación crónica de vía aérea con hiperreactividad y obstrucción variable.",
    clinical_clues: ["Sibilancias", "tos nocturna", "disnea episódica", "síntomas con desencadenantes"],
    red_flags: ["Silencio auscultatorio", "uso intenso de músculos accesorios", "cianosis", "alteración de conciencia"],
    nursing_priorities: ["Evaluar patrón respiratorio", "educación en inhaladores", "identificar desencadenantes", "plan de acción escrito"],
    diagnostic_support: ["Espirometría", "PEF seriado", "oximetría", "gasometría en crisis severa"],
  },
  {
    id: "epoc",
    name: "EPOC",
    area: "Respiratorio",
    urgency: "media",
    summary: "Limitación crónica al flujo aéreo, generalmente progresiva y asociada a exposición a humo.",
    clinical_clues: ["Tos crónica", "expectoración", "disnea progresiva", "intolerancia al esfuerzo"],
    red_flags: ["Exacerbación con hipercapnia", "somnolencia", "cianosis", "falla respiratoria"],
    nursing_priorities: ["Educación para dejar tabaco", "técnicas respiratorias", "uso correcto de broncodilatadores", "vacunación"],
    diagnostic_support: ["Espirometría posbroncodilatador", "radiografía de tórax", "gasometría", "hemograma"],
  },
  {
    id: "neumonia",
    name: "Neumonía adquirida en la comunidad",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Infección del parénquima pulmonar con compromiso respiratorio variable.",
    clinical_clues: ["Fiebre", "tos productiva", "dolor pleurítico", "taquipnea"],
    red_flags: ["SatO2 < 90%", "sepsis", "hipotensión", "confusión aguda"],
    nursing_priorities: ["Evaluar oxigenación", "control térmico e hidratación", "adherencia antibiótica", "vigilancia de signos de sepsis"],
    diagnostic_support: ["Radiografía de tórax", "hemograma y PCR", "oximetría", "hemocultivos según gravedad"],
  },
  {
    id: "acv",
    name: "Accidente cerebrovascular",
    area: "Neurológico",
    urgency: "alta",
    summary: "Déficit neurológico focal súbito por causa vascular.",
    clinical_clues: ["Hemiparesia", "disartria", "asimetría facial", "alteración súbita del lenguaje"],
    red_flags: ["Inicio < 4.5 h", "deterioro rápido del nivel de conciencia", "cefalea intensa súbita", "convulsión inicial"],
    nursing_priorities: ["Activar código ictus", "control de vía aérea y glucemia", "prevención de broncoaspiración", "registro de hora de inicio"],
    diagnostic_support: ["TAC de cráneo urgente", "glucosa capilar", "ECG", "laboratorios básicos"],
  },
  {
    id: "epilepsia",
    name: "Epilepsia",
    area: "Neurológico",
    urgency: "media",
    summary: "Predisposición persistente a crisis epilépticas recurrentes.",
    clinical_clues: ["Crisis motoras o focales", "periodo postictal", "antecedentes neurológicos"],
    red_flags: ["Estatus epiléptico", "trauma asociado grave", "déficit neurológico persistente", "primera crisis con fiebre alta en adulto"],
    nursing_priorities: ["Seguridad durante crisis", "adherencia a antiepilépticos", "educación familiar", "registro de características de crisis"],
    diagnostic_support: ["EEG", "neuroimagen según caso", "niveles de fármacos", "perfil metabólico"],
  },
  {
    id: "dm2",
    name: "Diabetes mellitus tipo 2",
    area: "Endocrino-metabólico",
    urgency: "media",
    summary: "Trastorno metabólico con hiperglucemia crónica por resistencia a insulina y déficit relativo.",
    clinical_clues: ["Poliuria", "polidipsia", "fatiga", "infecciones recurrentes"],
    red_flags: ["Cetoacidosis", "estado hiperosmolar", "hipoglucemia severa", "pie diabético infectado"],
    nursing_priorities: ["Educación en autocontrol glucémico", "plan alimentario", "adherencia farmacológica", "cuidado de pies"],
    diagnostic_support: ["Glucosa en ayunas", "HbA1c", "perfil lipídico", "función renal y microalbuminuria"],
  },
  {
    id: "hipotiroidismo",
    name: "Hipotiroidismo",
    area: "Endocrino-metabólico",
    urgency: "baja",
    summary: "Déficit de hormonas tiroideas con enlentecimiento metabólico.",
    clinical_clues: ["Fatiga", "aumento de peso", "piel seca", "estreñimiento"],
    red_flags: ["Coma mixedematoso", "bradicardia severa", "hipotermia", "somnolencia progresiva"],
    nursing_priorities: ["Educación sobre toma de levotiroxina", "seguimiento de síntomas", "adherencia a controles", "prevención de interacciones farmacológicas"],
    diagnostic_support: ["TSH", "T4 libre", "anticuerpos antitiroideos", "perfil lipídico"],
  },
  {
    id: "erc",
    name: "Enfermedad renal crónica",
    area: "Renal",
    urgency: "media",
    summary: "Disminución progresiva de función renal y/o daño renal persistente.",
    clinical_clues: ["Edema", "fatiga", "anemia", "alteraciones hidroelectrolíticas"],
    red_flags: ["Hiperkalemia", "sobrecarga hídrica severa", "acidosis metabólica", "síntomas urémicos"],
    nursing_priorities: ["Balance hídrico", "control de PA", "educación nutricional renal", "adherencia a nefroprotección"],
    diagnostic_support: ["TFG estimada", "creatinina", "uroanálisis y albuminuria", "electrolitos"],
  },
  {
    id: "ira",
    name: "Lesión renal aguda",
    area: "Renal",
    urgency: "alta",
    summary: "Deterioro súbito de la función renal con retención de productos nitrogenados.",
    clinical_clues: ["Oliguria", "aumento rápido de creatinina", "edema", "náusea"],
    red_flags: ["Anuria", "hiperkalemia severa", "edema pulmonar", "encefalopatía urémica"],
    nursing_priorities: ["Monitor diuresis horaria", "detectar nefrotóxicos", "control de volemia", "escalamiento temprano"],
    diagnostic_support: ["Creatinina seriada", "electrolitos", "uroanálisis", "ecografía renal"],
  },
  {
    id: "sepsis",
    name: "Sepsis",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Disfunción orgánica potencialmente mortal secundaria a respuesta desregulada a infección.",
    clinical_clues: ["Fiebre o hipotermia", "taquicardia", "taquipnea", "hipotensión"],
    red_flags: ["Lactato elevado", "oliguria", "alteración de conciencia", "shock"],
    nursing_priorities: ["Reconocimiento temprano", "protocolo primera hora", "control hemodinámico", "antibiótico oportuno"],
    diagnostic_support: ["Lactato", "hemocultivos", "hemograma", "función renal/hepática"],
  },
  {
    id: "itu",
    name: "Infección urinaria",
    area: "Infeccioso",
    urgency: "baja",
    summary: "Infección del tracto urinario inferior o superior según localización.",
    clinical_clues: ["Disuria", "polaquiuria", "urgencia miccional", "dolor suprapúbico"],
    red_flags: ["Fiebre alta con dolor lumbar", "sepsis urinaria", "embarazo con síntomas", "vómito persistente"],
    nursing_priorities: ["Educación en hidratación e higiene", "adherencia al antibiótico", "vigilancia de progresión a pielonefritis", "control de síntomas"],
    diagnostic_support: ["Uroanálisis", "urocultivo", "hemograma si fiebre", "ecografía si complicación"],
  },
  {
    id: "gastroenteritis",
    name: "Gastroenteritis aguda",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Proceso inflamatorio intestinal agudo con diarrea y posible deshidratación.",
    clinical_clues: ["Diarrea", "náusea", "vómito", "dolor abdominal tipo cólico"],
    red_flags: ["Deshidratación severa", "sangrado digestivo", "fiebre persistente alta", "alteración del estado mental"],
    nursing_priorities: ["Reposición hídrica", "balance hídrico", "vigilancia de signos de choque", "educación alimentaria"],
    diagnostic_support: ["Electrolitos", "coproanálisis según contexto", "hemograma", "función renal"],
  },
  {
    id: "apendicitis",
    name: "Apendicitis aguda",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Inflamación aguda del apéndice con riesgo de perforación.",
    clinical_clues: ["Dolor migratorio a fosa iliaca derecha", "náusea", "vómito", "fiebre"],
    red_flags: ["Peritonismo", "dolor generalizado", "inestabilidad hemodinámica", "sepsis abdominal"],
    nursing_priorities: ["Ayuno y preparación prequirúrgica", "control del dolor", "vigilancia de signos peritoneales", "educación perioperatoria"],
    diagnostic_support: ["Hemograma", "PCR", "ecografía", "TAC según caso"],
  },
  {
    id: "preeclampsia",
    name: "Preeclampsia",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Hipertensión gestacional con daño orgánico materno y riesgo fetal.",
    clinical_clues: ["PA elevada en embarazo", "cefalea", "fosfenos", "edema"],
    red_flags: ["Convulsiones", "dolor epigástrico intenso", "oliguria", "compromiso fetal"],
    nursing_priorities: ["Monitor materno-fetal", "control de PA", "detección de signos de eclampsia", "educación sobre alarma"],
    diagnostic_support: ["Proteinuria", "función hepática y renal", "plaquetas", "ecografía obstétrica"],
  },
  {
    id: "hemorragia-posparto",
    name: "Hemorragia posparto",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Pérdida sanguínea excesiva tras parto con riesgo de choque hipovolémico.",
    clinical_clues: ["Sangrado abundante", "taquicardia", "hipotensión", "palidez"],
    red_flags: ["Choque", "coagulopatía", "alteración del estado mental", "persistencia pese a medidas iniciales"],
    nursing_priorities: ["Activar protocolo obstétrico", "canalización y fluidos", "cuantificar sangrado", "apoyo emocional a paciente/familia"],
    diagnostic_support: ["Hemograma", "coagulación", "grupo y reserva de sangre", "ecografía si sospecha retención"],
  },
  {
    id: "bronquiolitis",
    name: "Bronquiolitis",
    area: "Pediatría",
    urgency: "media",
    summary: "Infección respiratoria baja en lactantes con obstrucción de vía aérea pequeña.",
    clinical_clues: ["Tos", "sibilancias", "taquipnea", "dificultad alimentaria"],
    red_flags: ["Apneas", "cianosis", "deshidratación", "hipoxemia persistente"],
    nursing_priorities: ["Soporte respiratorio", "higiene nasal", "hidratación", "educación a cuidadores"],
    diagnostic_support: ["Valoración clínica", "oximetría", "gasometría si grave", "imagen solo en casos seleccionados"],
  },
  {
    id: "dengue",
    name: "Dengue",
    area: "Infeccioso",
    urgency: "media",
    summary: "Arbovirosis con espectro de fiebre no complicada a formas graves con fuga capilar.",
    clinical_clues: ["Fiebre alta", "mialgias", "cefalea retroocular", "rash"],
    red_flags: ["Dolor abdominal intenso", "sangrado", "letargo", "hipotensión"],
    nursing_priorities: ["Hidratación controlada", "vigilancia de signos de alarma", "educación sobre retorno", "control de temperatura"],
    diagnostic_support: ["Hemograma seriado", "hematocrito", "plaquetas", "pruebas antigénicas/serológicas"],
  },
  {
    id: "shock-septico",
    name: "Shock séptico",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Forma grave de sepsis con hipotensión persistente y alteración de perfusión tisular.",
    clinical_clues: ["Hipotensión refractaria", "lactato elevado", "piel moteada", "oliguria"],
    red_flags: ["Falla multiorgánica", "hipoxemia grave", "deterioro neurológico", "acidosis progresiva"],
    nursing_priorities: ["Monitorización intensiva", "vasopresores según indicación", "control de perfusión", "prevención de lesiones por presión"],
    diagnostic_support: ["Lactato seriado", "gasometría", "hemocultivos", "perfil orgánico completo"],
  },
  {
    id: "politrauma",
    name: "Politrauma",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Compromiso multisistémico por trauma de alta energía.",
    clinical_clues: ["Lesiones múltiples", "dolor severo", "inestabilidad hemodinámica", "alteración neurológica"],
    red_flags: ["Compromiso de vía aérea", "hemorragia activa", "choque", "déficit neurológico progresivo"],
    nursing_priorities: ["Enfoque ABCDE", "control de hemorragia", "inmovilización y seguridad", "coordinación de equipo"],
    diagnostic_support: ["FAST", "TAC trauma", "hemograma/coagulación", "lactato"],
  },
  {
    id: "cetoacidosis",
    name: "Cetoacidosis diabética",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Descompensación metabólica aguda por déficit de insulina con cetosis y acidosis.",
    clinical_clues: ["Poliuria", "polidipsia", "dolor abdominal", "respiración de Kussmaul"],
    red_flags: ["Alteración de conciencia", "hipotensión", "hiperkalemia", "acidosis severa"],
    nursing_priorities: ["Hidratación guiada", "insulina protocolizada", "monitor electrolitos", "vigilancia neurológica"],
    diagnostic_support: ["Gasometría", "cetonas", "electrolitos", "glucosa seriada"],
  },
];

