import { MEDICAL_CASE_CATALOG, type MedicalCaseArea } from "./medicalCaseCatalog";

export type MedicalArea =
  | "Cardiovascular"
  | "Respiratorio"
  | "Neurológico"
  | "Endocrino-metabólico"
  | "Renal"
  | "Infeccioso"
  | "Gastrointestinal"
  | "Gineco-obstétrico"
  | "Pediatría"
  | "Geriátrico"
  | "Urgencias y críticos";

export type MedicalUrgency = "baja" | "media" | "alta";
export type MedicalCodeSystem = "CIE-10" | "DSM-5";

export type MedicalPathology = {
  id: string;
  name: string;
  area: MedicalArea;
  urgency: MedicalUrgency;
  codeSystem: MedicalCodeSystem;
  code: string;
  summary: string;
  clinical_clues: string[];
  red_flags: string[];
  nursing_priorities: string[];
  diagnostic_support: string[];
};

type MedicalPathologySeed = Omit<MedicalPathology, "codeSystem" | "code"> & {
  codeSystem?: MedicalCodeSystem;
  code?: string;
};

export const MEDICAL_AREAS: MedicalArea[] = [
  "Cardiovascular",
  "Respiratorio",
  "Neurológico",
  "Endocrino-metabólico",
  "Renal",
  "Infeccioso",
  "Gastrointestinal",
  "Gineco-obstétrico",
  "Pediatría",
  "Geriátrico",
  "Urgencias y críticos",
];

const EXTRA_MEDICAL_PATHOLOGY_LIBRARY: MedicalPathologySeed[] = [
  {
    id: "fibrilacion-auricular",
    name: "Fibrilación auricular",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Arritmia supraventricular frecuente con riesgo tromboembólico y descompensación hemodinámica.",
    clinical_clues: ["Palpitaciones", "disnea", "fatiga", "pulso irregular"],
    red_flags: ["Hipotensión", "dolor torácico", "síncope", "signos de ACV"],
    nursing_priorities: ["Monitor de ritmo", "control de frecuencia", "evaluar perfusión", "educar sobre adherencia anticoagulante"],
    diagnostic_support: ["ECG 12 derivaciones", "electrolitos", "función tiroidea", "ecocardiograma"],
  },
  {
    id: "embolia-pulmonar",
    name: "Embolia pulmonar",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Obstrucción arterial pulmonar con compromiso respiratorio y riesgo de inestabilidad.",
    clinical_clues: ["Disnea súbita", "dolor pleurítico", "taquicardia", "hipoxemia"],
    red_flags: ["Choque obstructivo", "síncope", "hipotensión", "deterioro respiratorio rápido"],
    nursing_priorities: ["Soporte de oxigenación", "monitor hemodinámico", "escalamiento temprano", "preparar anticoagulación según orden"],
    diagnostic_support: ["Angio-TAC pulmonar", "Dímero-D", "gasometría arterial", "ecografía venosa"],
  },
  {
    id: "trombosis-venosa-profunda",
    name: "Trombosis venosa profunda",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Formación de trombo venoso profundo con riesgo de embolia pulmonar.",
    clinical_clues: ["Edema unilateral", "dolor en pantorrilla", "aumento de temperatura local", "sensibilidad a la palpación"],
    red_flags: ["Disnea súbita", "dolor torácico", "hipoxemia", "taquicardia persistente"],
    nursing_priorities: ["Movilización segura", "vigilar progresión de edema", "educar sobre anticoagulación", "control de dolor"],
    diagnostic_support: ["Eco Doppler venoso", "Dímero-D", "perfil de coagulación", "estratificación de riesgo"],
  },
  {
    id: "endocarditis-infecciosa",
    name: "Endocarditis infecciosa",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Infección valvular con riesgo de embolización y falla cardiaca.",
    clinical_clues: ["Fiebre persistente", "soplo nuevo", "fatiga intensa", "fenómenos embólicos"],
    red_flags: ["Sepsis", "insuficiencia cardiaca aguda", "embolia cerebral", "bloqueo AV"],
    nursing_priorities: ["Control térmico y hemodinámico", "vigilancia neurológica", "adherencia antibiótica", "prevención de complicaciones embólicas"],
    diagnostic_support: ["Hemocultivos seriados", "ecocardiograma", "PCR/VSG", "hemograma"],
  },
  {
    id: "miocarditis-aguda",
    name: "Miocarditis aguda",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Inflamación miocárdica aguda con deterioro de función ventricular y arritmias.",
    clinical_clues: ["Dolor torácico", "disnea", "palpitaciones", "fatiga progresiva"],
    red_flags: ["Arritmias inestables", "choque cardiogénico", "hipotensión", "congestión pulmonar"],
    nursing_priorities: ["Monitor cardíaco continuo", "evaluar perfusión", "control de balance hídrico", "escalamiento a críticos si deteriora"],
    diagnostic_support: ["ECG", "troponinas", "ecocardiograma", "resonancia cardíaca"],
  },
  {
    id: "shock-cardiogenico",
    name: "Shock cardiogénico",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Falla severa de bomba con hipoperfusión tisular y alta mortalidad.",
    clinical_clues: ["Hipotensión persistente", "oliguria", "piel fría", "alteración mental"],
    red_flags: ["Acidosis láctica", "hipoxemia", "arritmias malignas", "falla multiorgánica"],
    nursing_priorities: ["Soporte hemodinámico intensivo", "monitorización invasiva según protocolo", "control de diuresis", "coordinación de equipo crítico"],
    diagnostic_support: ["Lactato", "ecocardiograma urgente", "gasometría", "perfil orgánico"],
  },
  {
    id: "insuficiencia-respiratoria-aguda",
    name: "Insuficiencia respiratoria aguda",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Fracaso de oxigenación y/o ventilación con riesgo de hipoxia tisular.",
    clinical_clues: ["Disnea intensa", "taquipnea", "uso de músculos accesorios", "SatO2 baja"],
    red_flags: ["Alteración de conciencia", "fatiga respiratoria", "hipercapnia severa", "cianosis"],
    nursing_priorities: ["Asegurar vía aérea", "oxigenoterapia escalonada", "monitor gasométrico", "preparar soporte ventilatorio"],
    diagnostic_support: ["Gasometría arterial", "oximetría continua", "radiografía de tórax", "analítica básica"],
  },
  {
    id: "sdra",
    name: "Síndrome de distrés respiratorio agudo (SDRA)",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Insuficiencia respiratoria hipoxémica grave por daño alveolocapilar difuso.",
    clinical_clues: ["Hipoxemia refractaria", "infiltrados bilaterales", "taquipnea", "deterioro rápido"],
    red_flags: ["Requerimiento de ventilación mecánica", "shock asociado", "acidosis respiratoria", "falla multiorgánica"],
    nursing_priorities: ["Manejo ventilatorio protector", "posición prono según criterio", "prevención de neumonía asociada", "vigilancia hemodinámica"],
    diagnostic_support: ["Gasometría seriada", "radiografía/TC de tórax", "índice PaO2/FiO2", "lactato"],
  },
  {
    id: "neumotorax",
    name: "Neumotórax",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Acumulación de aire pleural con colapso pulmonar parcial o total.",
    clinical_clues: ["Dolor torácico súbito", "disnea", "hipoventilación unilateral", "taquicardia"],
    red_flags: ["Desviación traqueal", "hipotensión", "ingurgitación yugular", "deterioro rápido"],
    nursing_priorities: ["Reconocimiento inmediato", "preparar drenaje pleural", "oxigenoterapia", "monitor de signos vitales"],
    diagnostic_support: ["Radiografía de tórax", "ecografía pulmonar", "gasometría", "evaluación clínica seriada"],
  },
  {
    id: "derrame-pleural",
    name: "Derrame pleural",
    area: "Respiratorio",
    urgency: "media",
    summary: "Acumulación de líquido pleural con compromiso respiratorio variable.",
    clinical_clues: ["Disnea progresiva", "dolor pleurítico", "matidez a la percusión", "murmullo disminuido"],
    red_flags: ["Hipoxemia", "fiebre alta persistente", "inestabilidad hemodinámica", "empiema"],
    nursing_priorities: ["Vigilancia respiratoria", "preparar toracocentesis", "control de dolor", "educación sobre signos de alarma"],
    diagnostic_support: ["Ecografía pleural", "radiografía de tórax", "análisis de líquido pleural", "hemograma"],
  },
  {
    id: "tuberculosis-pulmonar",
    name: "Tuberculosis pulmonar",
    area: "Respiratorio",
    urgency: "media",
    summary: "Infección pulmonar por Mycobacterium tuberculosis con impacto respiratorio y comunitario.",
    clinical_clues: ["Tos crónica", "pérdida de peso", "sudoración nocturna", "hemoptisis"],
    red_flags: ["Insuficiencia respiratoria", "hemoptisis masiva", "desnutrición severa", "coinfección compleja"],
    nursing_priorities: ["Aislamiento respiratorio", "adherencia a tratamiento", "rastreo de contactos", "soporte nutricional"],
    diagnostic_support: ["Baciloscopia", "GeneXpert", "radiografía de tórax", "cultivo de esputo"],
  },
  {
    id: "meningitis-bacteriana",
    name: "Meningitis bacteriana",
    area: "Neurológico",
    urgency: "alta",
    summary: "Infección meníngea aguda con riesgo de sepsis y daño neurológico.",
    clinical_clues: ["Fiebre", "cefalea intensa", "rigidez de nuca", "fotofobia"],
    red_flags: ["Alteración de conciencia", "convulsiones", "choque séptico", "déficit focal"],
    nursing_priorities: ["Aislamiento y bioseguridad", "monitor neurológico frecuente", "administración antibiótica oportuna", "control hemodinámico"],
    diagnostic_support: ["Punción lumbar", "hemocultivos", "TAC previo si indicado", "PCR inflamatoria"],
  },
  {
    id: "encefalitis-viral",
    name: "Encefalitis viral",
    area: "Neurológico",
    urgency: "alta",
    summary: "Inflamación cerebral infecciosa con alteraciones cognitivas y conductuales agudas.",
    clinical_clues: ["Fiebre", "confusión", "cefalea", "cambios conductuales"],
    red_flags: ["Convulsiones repetidas", "coma", "hipertensión endocraneana", "inestabilidad autonómica"],
    nursing_priorities: ["Vigilancia neurológica continua", "control de vía aérea", "manejo de convulsiones", "soporte familiar"],
    diagnostic_support: ["LCR por PCR", "RM cerebral", "EEG", "panel infeccioso"],
  },
  {
    id: "hemorragia-subaracnoidea",
    name: "Hemorragia subaracnoidea",
    area: "Neurológico",
    urgency: "alta",
    summary: "Sangrado subaracnoideo agudo con riesgo de vasoespasmo y deterioro neurológico rápido.",
    clinical_clues: ["Cefalea en trueno", "rigidez cervical", "náusea", "fotofobia"],
    red_flags: ["Disminución del nivel de conciencia", "déficit focal", "convulsiones", "inestabilidad hemodinámica"],
    nursing_priorities: ["Control neurológico seriado", "manejo hemodinámico estricto", "prevención de vasoespasmo", "escalamiento neurocrítico"],
    diagnostic_support: ["TAC cerebral urgente", "angiotomografía", "LCR si TAC negativa", "monitorización intensiva"],
  },
  {
    id: "trauma-craneoencefalico",
    name: "Trauma craneoencefálico",
    area: "Neurológico",
    urgency: "alta",
    summary: "Lesión cerebral traumática con gravedad variable y riesgo de hipertensión endocraneana.",
    clinical_clues: ["Cefalea", "vómito", "amnesia", "somnolencia"],
    red_flags: ["Glasgow < 13", "anisocoria", "deterioro progresivo", "déficit focal"],
    nursing_priorities: ["ABC inicial", "inmovilización cervical", "vigilancia Glasgow", "prevención de lesión secundaria"],
    diagnostic_support: ["TAC cerebral", "monitor neurológico", "gasometría", "perfil de coagulación"],
  },
  {
    id: "delirium-agudo",
    name: "Delirium agudo",
    area: "Neurológico",
    urgency: "media",
    summary: "Síndrome confusional agudo secundario a causa médica subyacente.",
    clinical_clues: ["Fluctuación de atención", "desorientación", "agitación o hipoactividad", "inversión sueño-vigilia"],
    red_flags: ["Compromiso respiratorio", "sepsis no reconocida", "caídas recurrentes", "auto/heteroagresión"],
    nursing_priorities: ["Entorno seguro", "reorientación frecuente", "buscar causa precipitante", "control de fármacos de riesgo"],
    diagnostic_support: ["Laboratorios metabólicos", "tamizaje infeccioso", "ECG", "imagen según sospecha"],
  },
  {
    id: "hipoglucemia-severa",
    name: "Hipoglucemia severa",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descenso crítico de glucosa con riesgo neurológico y cardiovascular.",
    clinical_clues: ["Diaforesis", "temblor", "confusión", "somnolencia"],
    red_flags: ["Convulsiones", "coma", "arritmias", "déficit neurológico persistente"],
    nursing_priorities: ["Corrección inmediata de glucosa", "monitorizar conciencia", "evitar recurrencia", "educación sobre prevención"],
    diagnostic_support: ["Glucosa capilar seriada", "perfil metabólico", "función renal", "revisión de esquema terapéutico"],
  },
  {
    id: "estado-hiperosmolar",
    name: "Estado hiperosmolar hiperglucémico",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descompensación hiperglucémica grave con deshidratación y alteración del sensorio.",
    clinical_clues: ["Polidipsia", "debilidad", "deshidratación", "hiperglucemia extrema"],
    red_flags: ["Shock", "deterioro neurológico", "insuficiencia renal", "trombosis"],
    nursing_priorities: ["Reposición hídrica protocolizada", "monitor electrolitos", "insulina según guía", "vigilancia neurológica"],
    diagnostic_support: ["Osmolaridad plasmática", "electrolitos", "gasometría", "glucosa seriada"],
  },
  {
    id: "tormenta-tiroidea",
    name: "Tormenta tiroidea",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Descompensación extrema del hipertiroidismo con riesgo vital.",
    clinical_clues: ["Fiebre alta", "taquicardia severa", "agitación", "diarrea"],
    red_flags: ["Arritmias", "insuficiencia cardiaca", "shock", "compromiso neurológico"],
    nursing_priorities: ["Control hemodinámico intensivo", "disminuir demanda metabólica", "administración terapéutica prescrita", "manejo térmico"],
    diagnostic_support: ["TSH/T4 libre", "ECG", "perfil hepático", "electrolitos"],
  },
  {
    id: "insuficiencia-suprarrenal-aguda",
    name: "Insuficiencia suprarrenal aguda",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Crisis adrenal con hipotensión y alteraciones electrolíticas severas.",
    clinical_clues: ["Debilidad intensa", "náusea/vómito", "hipotensión", "dolor abdominal"],
    red_flags: ["Shock refractario", "hiponatremia severa", "hiperkalemia", "alteración de conciencia"],
    nursing_priorities: ["Reposición de volumen", "monitorización hemodinámica", "administrar corticoides según orden", "vigilancia de electrolitos"],
    diagnostic_support: ["Cortisol basal", "electrolitos", "gasometría", "glucosa"],
  },
  {
    id: "hiponatremia-sintomatica",
    name: "Hiponatremia sintomática",
    area: "Endocrino-metabólico",
    urgency: "alta",
    summary: "Trastorno hidroelectrolítico con riesgo neurológico por edema cerebral.",
    clinical_clues: ["Náusea", "cefalea", "confusión", "letargo"],
    red_flags: ["Convulsiones", "coma", "deterioro rápido", "insuficiencia respiratoria"],
    nursing_priorities: ["Corrección controlada de sodio", "vigilancia neurológica", "balance hídrico estricto", "detección de causa de base"],
    diagnostic_support: ["Sodio sérico seriado", "osmolaridad plasmática/urinaria", "función renal", "electrolitos completos"],
  },
  {
    id: "pielonefritis-aguda",
    name: "Pielonefritis aguda",
    area: "Renal",
    urgency: "media",
    summary: "Infección urinaria alta con compromiso sistémico variable.",
    clinical_clues: ["Fiebre", "dolor lumbar", "disuria", "escalofríos"],
    red_flags: ["Sepsis urinaria", "hipotensión", "vómito persistente", "deterioro renal agudo"],
    nursing_priorities: ["Hidratación y control térmico", "vigilancia de sepsis", "adherencia antibiótica", "control de dolor"],
    diagnostic_support: ["Urocultivo", "uroanálisis", "hemograma", "función renal"],
  },
  {
    id: "litiasis-renal-obstructiva",
    name: "Litiasis renal obstructiva",
    area: "Renal",
    urgency: "media",
    summary: "Obstrucción urinaria por cálculo con dolor intenso y riesgo infeccioso.",
    clinical_clues: ["Cólico renal", "hematuria", "náusea", "inquietud psicomotora"],
    red_flags: ["Anuria", "fiebre alta", "sepsis urinaria", "dolor refractario"],
    nursing_priorities: ["Control del dolor", "monitor de diuresis", "vigilancia infecciosa", "preparar procedimientos de desobstrucción"],
    diagnostic_support: ["TAC simple renal", "ecografía renal", "uroanálisis", "creatinina sérica"],
  },
  {
    id: "glomerulonefritis-aguda",
    name: "Glomerulonefritis aguda",
    area: "Renal",
    urgency: "media",
    summary: "Inflamación glomerular con edema, hipertensión y deterioro de función renal.",
    clinical_clues: ["Edema periorbitario", "hematuria", "hipertensión", "oliguria"],
    red_flags: ["Hipertensión severa", "sobrecarga hídrica", "deterioro renal progresivo", "encefalopatía hipertensiva"],
    nursing_priorities: ["Balance hídrico", "control de presión arterial", "vigilancia renal", "educación en restricción salina"],
    diagnostic_support: ["EGO y proteinuria", "complemento sérico", "función renal", "ecografía renal"],
  },
  {
    id: "hiperpotasemia-grave",
    name: "Hiperpotasemia grave",
    area: "Renal",
    urgency: "alta",
    summary: "Elevación crítica de potasio con riesgo de arritmias fatales.",
    clinical_clues: ["Debilidad muscular", "parestesias", "náusea", "bradicardia"],
    red_flags: ["Arritmias en ECG", "bloqueo AV", "paro cardíaco", "hipotensión"],
    nursing_priorities: ["Monitor cardíaco continuo", "tratamiento corrector inmediato", "control seriado de potasio", "revisión de fármacos causales"],
    diagnostic_support: ["Electrolitos urgentes", "ECG", "función renal", "gasometría"],
  },
  {
    id: "celulitis-complicada",
    name: "Celulitis complicada",
    area: "Infeccioso",
    urgency: "media",
    summary: "Infección de piel y tejidos blandos con riesgo de extensión sistémica.",
    clinical_clues: ["Eritema", "dolor local", "calor", "edema"],
    red_flags: ["Fiebre alta persistente", "necrosis", "hipotensión", "rápida progresión"],
    nursing_priorities: ["Evaluar extensión de lesión", "control de dolor", "antibiótico oportuno", "educación sobre cuidados locales"],
    diagnostic_support: ["Hemograma", "PCR", "cultivo de exudado", "ecografía de partes blandas"],
  },
  {
    id: "neutropenia-febril",
    name: "Neutropenia febril",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Emergencia oncohematológica por infección potencial en paciente neutropénico.",
    clinical_clues: ["Fiebre >38°C", "malestar general", "escalofríos", "lesiones mucosas"],
    red_flags: ["Hipotensión", "sepsis", "deterioro respiratorio", "foco infeccioso invasivo"],
    nursing_priorities: ["Aislamiento protector", "hemocultivos tempranos", "antibiótico empírico rápido", "monitorización estrecha"],
    diagnostic_support: ["Hemograma urgente", "hemocultivos", "lactato", "radiografía de tórax"],
  },
  {
    id: "vih-avanzado",
    name: "VIH avanzado",
    area: "Infeccioso",
    urgency: "media",
    summary: "Inmunosupresión severa con riesgo de infecciones oportunistas y deterioro funcional.",
    clinical_clues: ["Pérdida de peso", "fiebre prolongada", "candidiasis recurrente", "debilidad"],
    red_flags: ["Infección oportunista grave", "insuficiencia respiratoria", "alteración neurológica", "sepsis"],
    nursing_priorities: ["Adherencia terapéutica", "tamizaje de oportunistas", "soporte nutricional", "acompañamiento psicosocial"],
    diagnostic_support: ["Carga viral", "CD4", "hemograma", "panel infeccioso dirigido"],
  },
  {
    id: "infeccion-intraabdominal",
    name: "Infección intraabdominal complicada",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Proceso infeccioso abdominal con riesgo de sepsis y peritonitis.",
    clinical_clues: ["Dolor abdominal difuso", "fiebre", "náusea/vómito", "taquicardia"],
    red_flags: ["Hipotensión", "defensa involuntaria", "lactato elevado", "oliguria"],
    nursing_priorities: ["Resucitación inicial", "vigilancia de sepsis", "control de dolor", "preparar intervención quirúrgica si indicada"],
    diagnostic_support: ["TAC abdominal", "hemocultivos", "lactato", "hemograma y PCR"],
  },
  {
    id: "fiebre-origen-desconocido",
    name: "Fiebre de origen desconocido",
    area: "Infeccioso",
    urgency: "media",
    summary: "Síndrome febril prolongado sin etiología inicial clara.",
    clinical_clues: ["Fiebre persistente", "astenia", "sudoración nocturna", "pérdida de peso"],
    red_flags: ["Inestabilidad hemodinámica", "deterioro respiratorio", "compromiso neurológico", "inmunosupresión severa"],
    nursing_priorities: ["Monitor térmico y hemodinámico", "registro clínico dirigido", "apoyo diagnóstico escalonado", "educación sobre signos de alarma"],
    diagnostic_support: ["Hemocultivos seriados", "imagen dirigida", "perfil inflamatorio", "estudios microbiológicos"],
  },
  {
    id: "pancreatitis-aguda",
    name: "Pancreatitis aguda",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Inflamación aguda pancreática con riesgo de falla orgánica en formas severas.",
    clinical_clues: ["Dolor epigástrico intenso", "náusea/vómito", "distensión abdominal", "taquicardia"],
    red_flags: ["Hipotensión", "hipoxemia", "oliguria", "deterioro metabólico"],
    nursing_priorities: ["Reposición hídrica", "control de dolor", "monitor de complicaciones", "soporte nutricional progresivo"],
    diagnostic_support: ["Lipasa sérica", "TAC abdominal", "hemoconcentración", "perfil metabólico"],
  },
  {
    id: "colecistitis-aguda",
    name: "Colecistitis aguda",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Inflamación vesicular aguda, usualmente litiásica, con dolor y fiebre.",
    clinical_clues: ["Dolor en hipocondrio derecho", "fiebre", "náusea", "Murphy positivo"],
    red_flags: ["Sepsis biliar", "perforación", "ictericia progresiva", "dolor refractario"],
    nursing_priorities: ["Ayuno y analgesia", "control térmico", "vigilancia de sepsis", "preparación para resolución quirúrgica"],
    diagnostic_support: ["Ecografía hepatobiliar", "hemograma", "perfil hepático", "PCR"],
  },
  {
    id: "hemorragia-digestiva-alta",
    name: "Hemorragia digestiva alta",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Sangrado de tracto digestivo superior con riesgo de choque hipovolémico.",
    clinical_clues: ["Hematemesis", "melenas", "palidez", "taquicardia"],
    red_flags: ["Hipotensión", "síncope", "sangrado activo masivo", "alteración de conciencia"],
    nursing_priorities: ["ABC y vía venosa", "cuantificar sangrado", "monitor hemodinámico", "preparar endoscopia urgente"],
    diagnostic_support: ["Hemograma seriado", "coagulación", "grupo y cruce", "endoscopia digestiva alta"],
  },
  {
    id: "obstruccion-intestinal",
    name: "Obstrucción intestinal",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Interrupción del tránsito intestinal con riesgo de isquemia y perforación.",
    clinical_clues: ["Dolor cólico", "distensión", "vómito", "ausencia de evacuaciones"],
    red_flags: ["Peritonitis", "fiebre alta", "hipotensión", "acidosis metabólica"],
    nursing_priorities: ["Descompresión si indicada", "balance hídrico", "control de dolor", "vigilancia de sepsis"],
    diagnostic_support: ["Radiografía abdominal", "TAC", "electrolitos", "lactato"],
  },
  {
    id: "cirrosis-descompensada",
    name: "Cirrosis descompensada",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Enfermedad hepática avanzada con ascitis, encefalopatía y riesgo hemorrágico.",
    clinical_clues: ["Ascitis", "ictericia", "edema", "fatiga intensa"],
    red_flags: ["Encefalopatía grave", "hemorragia variceal", "peritonitis bacteriana", "insuficiencia renal"],
    nursing_priorities: ["Control de balance", "vigilancia neurológica", "prevención de sangrado", "educación en adherencia"],
    diagnostic_support: ["Perfil hepático", "coagulación", "paracentesis diagnóstica", "función renal"],
  },
  {
    id: "embarazo-ectopico",
    name: "Embarazo ectópico",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Implantación extrauterina con riesgo de ruptura y hemorragia interna.",
    clinical_clues: ["Dolor pélvico", "amenorrea", "sangrado vaginal", "mareo"],
    red_flags: ["Inestabilidad hemodinámica", "dolor abdominal intenso", "síncope", "signos de choque"],
    nursing_priorities: ["Monitor hemodinámico", "vía venosa y fluidos", "preparar intervención urgente", "apoyo emocional"],
    diagnostic_support: ["Beta-hCG seriada", "ecografía transvaginal", "hemograma", "grupo y factor"],
  },
  {
    id: "amenaza-parto-pretermino",
    name: "Amenaza de parto pretérmino",
    area: "Gineco-obstétrico",
    urgency: "media",
    summary: "Actividad uterina y cambios cervicales antes de término con riesgo neonatal.",
    clinical_clues: ["Contracciones regulares", "dolor lumbar", "presión pélvica", "cambios cervicales"],
    red_flags: ["Rotura de membranas", "sangrado moderado-alto", "fiebre materna", "sufrimiento fetal"],
    nursing_priorities: ["Monitor materno-fetal", "reposo relativo según indicación", "educación de alarma", "coordinación obstétrica"],
    diagnostic_support: ["Tococardiografía", "ecografía cervical", "laboratorio infeccioso", "evaluación obstétrica seriada"],
  },
  {
    id: "placenta-previa",
    name: "Placenta previa con sangrado",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Implantación placentaria baja con hemorragia obstétrica potencialmente severa.",
    clinical_clues: ["Sangrado rojo rutilante", "ausencia de dolor intenso", "palidez", "taquicardia"],
    red_flags: ["Sangrado abundante", "hipotensión", "compromiso fetal", "choque"],
    nursing_priorities: ["Cuantificar sangrado", "monitorización fetal", "preparar hemoderivados", "escalamiento obstétrico"],
    diagnostic_support: ["Ecografía obstétrica", "hemograma", "coagulación", "grupo y reserva"],
  },
  {
    id: "infeccion-puerperal",
    name: "Infección puerperal",
    area: "Gineco-obstétrico",
    urgency: "media",
    summary: "Proceso infeccioso posparto con riesgo de sepsis materna.",
    clinical_clues: ["Fiebre posparto", "dolor pélvico", "loquios fétidos", "malestar general"],
    red_flags: ["Hipotensión", "taquicardia persistente", "dolor abdominal severo", "sepsis"],
    nursing_priorities: ["Detección temprana de sepsis", "manejo antibiótico", "higiene y cuidados perineales", "educación para seguimiento"],
    diagnostic_support: ["Hemograma", "cultivos", "PCR", "ecografía pélvica"],
  },
  {
    id: "aborto-incompleto",
    name: "Aborto incompleto complicado",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Retención de tejido gestacional con sangrado y riesgo infeccioso.",
    clinical_clues: ["Sangrado vaginal", "dolor tipo cólico", "expulsión parcial de tejido", "debilidad"],
    red_flags: ["Hemorragia activa", "fiebre", "hipotensión", "signos de sepsis"],
    nursing_priorities: ["Control hemodinámico", "manejo del dolor", "preparar evacuación uterina", "acompañamiento emocional"],
    diagnostic_support: ["Ecografía transvaginal", "hemograma", "Beta-hCG", "grupo y factor Rh"],
  },
  {
    id: "crup",
    name: "Crup (laringotraqueítis)",
    area: "Pediatría",
    urgency: "media",
    summary: "Inflamación de vía aérea superior pediátrica con tos perruna y estridor.",
    clinical_clues: ["Tos perruna", "estridor inspiratorio", "disfonía", "agitación nocturna"],
    red_flags: ["Estridor en reposo", "tirajes severos", "cianosis", "fatiga respiratoria"],
    nursing_priorities: ["Mantener calma del niño", "oxigenación y nebulización según orden", "vigilar trabajo respiratorio", "educar cuidadores"],
    diagnostic_support: ["Valoración clínica", "oximetría", "escala de severidad", "imagen solo si duda diagnóstica"],
  },
  {
    id: "neumonia-pediatrica",
    name: "Neumonía pediátrica",
    area: "Pediatría",
    urgency: "media",
    summary: "Infección respiratoria baja en niños con riesgo de hipoxemia y sepsis.",
    clinical_clues: ["Fiebre", "tos", "taquipnea", "tirajes"],
    red_flags: ["SatO2 baja", "apneas", "deshidratación", "compromiso del estado general"],
    nursing_priorities: ["Soporte respiratorio", "hidratación", "antibiótico según indicación", "educación familiar"],
    diagnostic_support: ["Radiografía de tórax", "oximetría", "hemograma", "PCR"],
  },
  {
    id: "deshidratacion-aguda-pediatrica",
    name: "Deshidratación aguda pediátrica",
    area: "Pediatría",
    urgency: "media",
    summary: "Déficit hídrico en niño con riesgo de choque hipovolémico.",
    clinical_clues: ["Mucosas secas", "llanto sin lágrimas", "taquicardia", "llenado capilar lento"],
    red_flags: ["Letargia", "anuria", "hipotensión", "alteración de conciencia"],
    nursing_priorities: ["Reposición hídrica según plan", "monitor de diuresis", "control de signos vitales", "educación en hidratación oral"],
    diagnostic_support: ["Electrolitos", "gases venosos", "glucosa", "evaluación clínica seriada"],
  },
  {
    id: "convulsion-febril-compleja",
    name: "Convulsión febril compleja",
    area: "Pediatría",
    urgency: "alta",
    summary: "Crisis convulsiva febril con características atípicas que requieren estudio ampliado.",
    clinical_clues: ["Convulsión >15 min", "focalidad", "recurrencia en 24h", "fiebre"],
    red_flags: ["Estado postictal prolongado", "meningismo", "deterioro neurológico", "compromiso respiratorio"],
    nursing_priorities: ["Asegurar vía aérea", "control de temperatura", "vigilancia neurológica", "contención familiar"],
    diagnostic_support: ["Glucosa capilar", "electrolitos", "evaluación neurológica", "punción lumbar según criterio"],
  },
  {
    id: "sepsis-neonatal",
    name: "Sepsis neonatal",
    area: "Pediatría",
    urgency: "alta",
    summary: "Infección sistémica neonatal con alta morbimortalidad sin tratamiento precoz.",
    clinical_clues: ["Letargia", "rechazo al alimento", "inestabilidad térmica", "dificultad respiratoria"],
    red_flags: ["Apneas", "choque", "hipoglucemia persistente", "convulsiones"],
    nursing_priorities: ["Monitor cardiorrespiratorio", "acceso vascular seguro", "antibiótico temprano", "soporte térmico"],
    diagnostic_support: ["Hemocultivo", "hemograma", "PCR/procalcitonina", "gases y glucosa"],
  },
  {
    id: "anafilaxia",
    name: "Anafilaxia",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Reacción de hipersensibilidad sistémica grave con riesgo de obstrucción aérea y choque.",
    clinical_clues: ["Urticaria", "edema facial", "sibilancias", "hipotensión"],
    red_flags: ["Compromiso de vía aérea", "estridor", "choque", "deterioro rápido"],
    nursing_priorities: ["Adrenalina inmediata según protocolo", "ABC y oxígeno", "monitorización continua", "preparar manejo avanzado de vía aérea"],
    diagnostic_support: ["Diagnóstico clínico inmediato", "monitor hemodinámico", "gasometría según gravedad", "triptasa si disponible"],
  },
  {
    id: "paro-cardiorrespiratorio",
    name: "Paro cardiorrespiratorio",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Cese de actividad circulatoria y respiratoria que requiere RCP inmediata.",
    clinical_clues: ["Ausencia de pulso", "inconsciencia", "apnea o respiración agónica", "cianosis"],
    red_flags: ["Ritmo desfibrilable", "no respuesta a RCP inicial", "hipoxia grave", "causas reversibles no corregidas"],
    nursing_priorities: ["RCP de alta calidad", "desfibrilación oportuna", "manejo de vía aérea", "coordinación del equipo de reanimación"],
    diagnostic_support: ["Monitor/ECG", "gasometría", "electrolitos", "evaluación de H y T"],
  },
  {
    id: "sangrado-masivo",
    name: "Sangrado masivo",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Hemorragia aguda severa con riesgo de choque y coagulopatía.",
    clinical_clues: ["Hipotensión", "taquicardia", "palidez", "sangrado activo"],
    red_flags: ["Choque refractario", "coagulopatía", "acidosis", "hipotermia"],
    nursing_priorities: ["Control de foco hemorrágico", "activación de protocolo de transfusión", "monitor hemodinámico", "calentamiento activo"],
    diagnostic_support: ["Hemograma seriado", "coagulación", "lactato", "grupo y reserva sanguínea"],
  },
  {
    id: "intoxicacion-aguda",
    name: "Intoxicación aguda",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Exposición tóxica con compromiso neurológico, respiratorio o hemodinámico.",
    clinical_clues: ["Alteración de conciencia", "náusea/vómito", "cambios pupilares", "inestabilidad autonómica"],
    red_flags: ["Depresión respiratoria", "convulsiones", "arritmias", "coma"],
    nursing_priorities: ["ABC y soporte vital", "descontaminación según protocolo", "identificar tóxico probable", "consulta toxicológica"],
    diagnostic_support: ["Gases arteriales", "toxicología dirigida", "electrolitos", "ECG"],
  },
  {
    id: "estatus-asmatico",
    name: "Estatus asmático",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Exacerbación asmática grave refractaria al tratamiento inicial.",
    clinical_clues: ["Disnea intensa", "sibilancias difusas", "taquicardia", "dificultad para hablar"],
    red_flags: ["Silencio auscultatorio", "fatiga respiratoria", "hipoxemia persistente", "hipercapnia"],
    nursing_priorities: ["Broncodilatación intensiva", "oxígeno escalonado", "vigilancia ventilatoria", "preparar soporte avanzado"],
    diagnostic_support: ["Oximetría continua", "gasometría", "PEF seriado", "radiografía según evolución"],
  },
  {
    id: "quemaduras-graves",
    name: "Quemaduras graves",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Lesión térmica extensa con riesgo de choque, infección y falla orgánica.",
    clinical_clues: ["Dolor intenso", "ampollas/escaras", "pérdida de líquidos", "taquicardia"],
    red_flags: ["Compromiso de vía aérea", "hipotensión", "superficie corporal extensa", "inhalación de humo"],
    nursing_priorities: ["ABC inicial", "reposición hídrica por fórmula", "analgesia", "prevención de infección y pérdida térmica"],
    diagnostic_support: ["Cálculo de SCQ", "gasometría", "electrolitos", "carboxihemoglobina si humo"],
  },
];

const BASE_MEDICAL_PATHOLOGY_LIBRARY: MedicalPathologySeed[] = [
  {
    id: "hta",
    name: "Hipertensión arterial",
    area: "Cardiovascular",
    urgency: "media",
    summary: "Elevación sostenida de presión arterial con riesgo de daño de órgano blanco.",
    clinical_clues: ["Cefalea ocasional", "mareo", "lecturas elevadas repetidas", "asintomática en fases iniciales"],
    red_flags: ["Crisis hipertensiva", "dolor torácico", "déficit neurológico agudo", "disnea súbita"],
    nursing_priorities: ["Toma correcta de PA", "adherencia terapéutica", "educación en estilo de vida", "seguimiento periódico"],
    diagnostic_support: ["Monitoreo ambulatorio de PA", "creatinina y electrolitos", "ECG", "fondo de ojo si aplica"],
  },
  {
    id: "iac",
    name: "Insuficiencia cardiaca",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Síndrome de falla de bomba con congestión y deterioro de perfusión.",
    clinical_clues: ["Disnea de esfuerzo", "edema periférico", "ortopnea", "fatiga"],
    red_flags: ["Edema agudo de pulmón", "hipotensión", "hipoxemia refractaria", "alteración del estado mental"],
    nursing_priorities: ["Balance hídrico estricto", "control de peso", "monitorización respiratoria", "educación sobre restricción de sodio"],
    diagnostic_support: ["BNP/NT-proBNP", "radiografía de tórax", "ecocardiograma", "función renal"],
  },
  {
    id: "sca",
    name: "Síndrome coronario agudo",
    area: "Cardiovascular",
    urgency: "alta",
    summary: "Isquemia miocárdica aguda por obstrucción coronaria.",
    clinical_clues: ["Dolor torácico opresivo", "diaforesis", "náuseas", "irradiación a brazo o mandíbula"],
    red_flags: ["Inestabilidad hemodinámica", "arritmias malignas", "dolor persistente >20 min", "síncope"],
    nursing_priorities: ["Activar protocolo de dolor torácico", "monitor cardíaco", "oxigenación según necesidad", "preparar para reperfusión"],
    diagnostic_support: ["ECG seriado", "troponinas", "radiografía de tórax", "estratificación de riesgo"],
  },
  {
    id: "asma",
    name: "Asma bronquial",
    area: "Respiratorio",
    urgency: "media",
    summary: "Inflamación crónica de vía aérea con hiperreactividad y obstrucción variable.",
    clinical_clues: ["Sibilancias", "tos nocturna", "disnea episódica", "síntomas con desencadenantes"],
    red_flags: ["Silencio auscultatorio", "uso intenso de músculos accesorios", "cianosis", "alteración de conciencia"],
    nursing_priorities: ["Evaluar patrón respiratorio", "educación en inhaladores", "identificar desencadenantes", "plan de acción escrito"],
    diagnostic_support: ["Espirometría", "PEF seriado", "oximetría", "gasometría en crisis severa"],
  },
  {
    id: "epoc",
    name: "EPOC",
    area: "Respiratorio",
    urgency: "media",
    summary: "Limitación crónica al flujo aéreo, generalmente progresiva y asociada a exposición a humo.",
    clinical_clues: ["Tos crónica", "expectoración", "disnea progresiva", "intolerancia al esfuerzo"],
    red_flags: ["Exacerbación con hipercapnia", "somnolencia", "cianosis", "falla respiratoria"],
    nursing_priorities: ["Educación para dejar tabaco", "técnicas respiratorias", "uso correcto de broncodilatadores", "vacunación"],
    diagnostic_support: ["Espirometría posbroncodilatador", "radiografía de tórax", "gasometría", "hemograma"],
  },
  {
    id: "neumonia",
    name: "Neumonía adquirida en la comunidad",
    area: "Respiratorio",
    urgency: "alta",
    summary: "Infección del parénquima pulmonar con compromiso respiratorio variable.",
    clinical_clues: ["Fiebre", "tos productiva", "dolor pleurítico", "taquipnea"],
    red_flags: ["SatO2 < 90%", "sepsis", "hipotensión", "confusión aguda"],
    nursing_priorities: ["Evaluar oxigenación", "control térmico e hidratación", "adherencia antibiótica", "vigilancia de signos de sepsis"],
    diagnostic_support: ["Radiografía de tórax", "hemograma y PCR", "oximetría", "hemocultivos según gravedad"],
  },
  {
    id: "acv",
    name: "Accidente cerebrovascular",
    area: "Neurológico",
    urgency: "alta",
    summary: "Déficit neurológico focal súbito por causa vascular.",
    clinical_clues: ["Hemiparesia", "disartria", "asimetría facial", "alteración súbita del lenguaje"],
    red_flags: ["Inicio < 4.5 h", "deterioro rápido del nivel de conciencia", "cefalea intensa súbita", "convulsión inicial"],
    nursing_priorities: ["Activar código ictus", "control de vía aérea y glucemia", "prevención de broncoaspiración", "registro de hora de inicio"],
    diagnostic_support: ["TAC de cráneo urgente", "glucosa capilar", "ECG", "laboratorios básicos"],
  },
  {
    id: "epilepsia",
    name: "Epilepsia",
    area: "Neurológico",
    urgency: "media",
    summary: "Predisposición persistente a crisis epilépticas recurrentes.",
    clinical_clues: ["Crisis motoras o focales", "periodo postictal", "antecedentes neurológicos"],
    red_flags: ["Estatus epiléptico", "trauma asociado grave", "déficit neurológico persistente", "primera crisis con fiebre alta en adulto"],
    nursing_priorities: ["Seguridad durante crisis", "adherencia a antiepilépticos", "educación familiar", "registro de características de crisis"],
    diagnostic_support: ["EEG", "neuroimagen según caso", "niveles de fármacos", "perfil metabólico"],
  },
  {
    id: "dm2",
    name: "Diabetes mellitus tipo 2",
    area: "Endocrino-metabólico",
    urgency: "media",
    summary: "Trastorno metabólico con hiperglucemia crónica por resistencia a insulina y déficit relativo.",
    clinical_clues: ["Poliuria", "polidipsia", "fatiga", "infecciones recurrentes"],
    red_flags: ["Cetoacidosis", "estado hiperosmolar", "hipoglucemia severa", "pie diabético infectado"],
    nursing_priorities: ["Educación en autocontrol glucémico", "plan alimentario", "adherencia farmacológica", "cuidado de pies"],
    diagnostic_support: ["Glucosa en ayunas", "HbA1c", "perfil lipídico", "función renal y microalbuminuria"],
  },
  {
    id: "hipotiroidismo",
    name: "Hipotiroidismo",
    area: "Endocrino-metabólico",
    urgency: "baja",
    summary: "Déficit de hormonas tiroideas con enlentecimiento metabólico.",
    clinical_clues: ["Fatiga", "aumento de peso", "piel seca", "estreñimiento"],
    red_flags: ["Coma mixedematoso", "bradicardia severa", "hipotermia", "somnolencia progresiva"],
    nursing_priorities: ["Educación sobre toma de levotiroxina", "seguimiento de síntomas", "adherencia a controles", "prevención de interacciones farmacológicas"],
    diagnostic_support: ["TSH", "T4 libre", "anticuerpos antitiroideos", "perfil lipídico"],
  },
  {
    id: "erc",
    name: "Enfermedad renal crónica",
    area: "Renal",
    urgency: "media",
    summary: "Disminución progresiva de función renal y/o daño renal persistente.",
    clinical_clues: ["Edema", "fatiga", "anemia", "alteraciones hidroelectrolíticas"],
    red_flags: ["Hiperkalemia", "sobrecarga hídrica severa", "acidosis metabólica", "síntomas urémicos"],
    nursing_priorities: ["Balance hídrico", "control de PA", "educación nutricional renal", "adherencia a nefroprotección"],
    diagnostic_support: ["TFG estimada", "creatinina", "uroanálisis y albuminuria", "electrolitos"],
  },
  {
    id: "ira",
    name: "Lesión renal aguda",
    area: "Renal",
    urgency: "alta",
    summary: "Deterioro súbito de la función renal con retención de productos nitrogenados.",
    clinical_clues: ["Oliguria", "aumento rápido de creatinina", "edema", "náusea"],
    red_flags: ["Anuria", "hiperkalemia severa", "edema pulmonar", "encefalopatía urémica"],
    nursing_priorities: ["Monitor diuresis horaria", "detectar nefrotóxicos", "control de volemia", "escalamiento temprano"],
    diagnostic_support: ["Creatinina seriada", "electrolitos", "uroanálisis", "ecografía renal"],
  },
  {
    id: "sepsis",
    name: "Sepsis",
    area: "Infeccioso",
    urgency: "alta",
    summary: "Disfunción orgánica potencialmente mortal secundaria a respuesta desregulada a infección.",
    clinical_clues: ["Fiebre o hipotermia", "taquicardia", "taquipnea", "hipotensión"],
    red_flags: ["Lactato elevado", "oliguria", "alteración de conciencia", "shock"],
    nursing_priorities: ["Reconocimiento temprano", "protocolo primera hora", "control hemodinámico", "antibiótico oportuno"],
    diagnostic_support: ["Lactato", "hemocultivos", "hemograma", "función renal/hepática"],
  },
  {
    id: "itu",
    name: "Infección urinaria",
    area: "Infeccioso",
    urgency: "baja",
    summary: "Infección del tracto urinario inferior o superior según localización.",
    clinical_clues: ["Disuria", "polaquiuria", "urgencia miccional", "dolor suprapúbico"],
    red_flags: ["Fiebre alta con dolor lumbar", "sepsis urinaria", "embarazo con síntomas", "vómito persistente"],
    nursing_priorities: ["Educación en hidratación e higiene", "adherencia al antibiótico", "vigilancia de progresión a pielonefritis", "control de síntomas"],
    diagnostic_support: ["Uroanálisis", "urocultivo", "hemograma si fiebre", "ecografía si complicación"],
  },
  {
    id: "gastroenteritis",
    name: "Gastroenteritis aguda",
    area: "Gastrointestinal",
    urgency: "media",
    summary: "Proceso inflamatorio intestinal agudo con diarrea y posible deshidratación.",
    clinical_clues: ["Diarrea", "náusea", "vómito", "dolor abdominal tipo cólico"],
    red_flags: ["Deshidratación severa", "sangrado digestivo", "fiebre persistente alta", "alteración del estado mental"],
    nursing_priorities: ["Reposición hídrica", "balance hídrico", "vigilancia de signos de choque", "educación alimentaria"],
    diagnostic_support: ["Electrolitos", "coproanálisis según contexto", "hemograma", "función renal"],
  },
  {
    id: "apendicitis",
    name: "Apendicitis aguda",
    area: "Gastrointestinal",
    urgency: "alta",
    summary: "Inflamación aguda del apéndice con riesgo de perforación.",
    clinical_clues: ["Dolor migratorio a fosa iliaca derecha", "náusea", "vómito", "fiebre"],
    red_flags: ["Peritonismo", "dolor generalizado", "inestabilidad hemodinámica", "sepsis abdominal"],
    nursing_priorities: ["Ayuno y preparación prequirúrgica", "control del dolor", "vigilancia de signos peritoneales", "educación perioperatoria"],
    diagnostic_support: ["Hemograma", "PCR", "ecografía", "TAC según caso"],
  },
  {
    id: "preeclampsia",
    name: "Preeclampsia",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Hipertensión gestacional con daño orgánico materno y riesgo fetal.",
    clinical_clues: ["PA elevada en embarazo", "cefalea", "fosfenos", "edema"],
    red_flags: ["Convulsiones", "dolor epigástrico intenso", "oliguria", "compromiso fetal"],
    nursing_priorities: ["Monitor materno-fetal", "control de PA", "detección de signos de eclampsia", "educación sobre alarma"],
    diagnostic_support: ["Proteinuria", "función hepática y renal", "plaquetas", "ecografía obstétrica"],
  },
  {
    id: "hemorragia-posparto",
    name: "Hemorragia posparto",
    area: "Gineco-obstétrico",
    urgency: "alta",
    summary: "Pérdida sanguínea excesiva tras parto con riesgo de choque hipovolémico.",
    clinical_clues: ["Sangrado abundante", "taquicardia", "hipotensión", "palidez"],
    red_flags: ["Choque", "coagulopatía", "alteración del estado mental", "persistencia pese a medidas iniciales"],
    nursing_priorities: ["Activar protocolo obstétrico", "canalización y fluidos", "cuantificar sangrado", "apoyo emocional a paciente/familia"],
    diagnostic_support: ["Hemograma", "coagulación", "grupo y reserva de sangre", "ecografía si sospecha retención"],
  },
  {
    id: "bronquiolitis",
    name: "Bronquiolitis",
    area: "Pediatría",
    urgency: "media",
    summary: "Infección respiratoria baja en lactantes con obstrucción de vía aérea pequeña.",
    clinical_clues: ["Tos", "sibilancias", "taquipnea", "dificultad alimentaria"],
    red_flags: ["Apneas", "cianosis", "deshidratación", "hipoxemia persistente"],
    nursing_priorities: ["Soporte respiratorio", "higiene nasal", "hidratación", "educación a cuidadores"],
    diagnostic_support: ["Valoración clínica", "oximetría", "gasometría si grave", "imagen solo en casos seleccionados"],
  },
  {
    id: "dengue",
    name: "Dengue",
    area: "Infeccioso",
    urgency: "media",
    summary: "Arbovirosis con espectro de fiebre no complicada a formas graves con fuga capilar.",
    clinical_clues: ["Fiebre alta", "mialgias", "cefalea retroocular", "rash"],
    red_flags: ["Dolor abdominal intenso", "sangrado", "letargo", "hipotensión"],
    nursing_priorities: ["Hidratación controlada", "vigilancia de signos de alarma", "educación sobre retorno", "control de temperatura"],
    diagnostic_support: ["Hemograma seriado", "hematocrito", "plaquetas", "pruebas antigénicas/serológicas"],
  },
  {
    id: "shock-septico",
    name: "Shock séptico",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Forma grave de sepsis con hipotensión persistente y alteración de perfusión tisular.",
    clinical_clues: ["Hipotensión refractaria", "lactato elevado", "piel moteada", "oliguria"],
    red_flags: ["Falla multiorgánica", "hipoxemia grave", "deterioro neurológico", "acidosis progresiva"],
    nursing_priorities: ["Monitorización intensiva", "vasopresores según indicación", "control de perfusión", "prevención de lesiones por presión"],
    diagnostic_support: ["Lactato seriado", "gasometría", "hemocultivos", "perfil orgánico completo"],
  },
  {
    id: "politrauma",
    name: "Politrauma",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Compromiso multisistémico por trauma de alta energía.",
    clinical_clues: ["Lesiones múltiples", "dolor severo", "inestabilidad hemodinámica", "alteración neurológica"],
    red_flags: ["Compromiso de vía aérea", "hemorragia activa", "choque", "déficit neurológico progresivo"],
    nursing_priorities: ["Enfoque ABCDE", "control de hemorragia", "inmovilización y seguridad", "coordinación de equipo"],
    diagnostic_support: ["FAST", "TAC trauma", "hemograma/coagulación", "lactato"],
  },
  {
    id: "cetoacidosis",
    name: "Cetoacidosis diabética",
    area: "Urgencias y críticos",
    urgency: "alta",
    summary: "Descompensación metabólica aguda por déficit de insulina con cetosis y acidosis.",
    clinical_clues: ["Poliuria", "polidipsia", "dolor abdominal", "respiración de Kussmaul"],
    red_flags: ["Alteración de conciencia", "hipotensión", "hiperkalemia", "acidosis severa"],
    nursing_priorities: ["Hidratación guiada", "insulina protocolizada", "monitor electrolitos", "vigilancia neurológica"],
    diagnostic_support: ["Gasometría", "cetonas", "electrolitos", "glucosa seriada"],
  },
];

const TARGET_MEDICAL_PATHOLOGY_COUNT = 200;

const CASE_AREA_TO_MEDICAL_AREA: Record<MedicalCaseArea, MedicalArea> = {
  Cardiovascular: "Cardiovascular",
  Respiratorio: "Respiratorio",
  "Neurológico": "Neurológico",
  "Endocrino-metabólico": "Endocrino-metabólico",
  "Renal-urinario": "Renal",
  Infeccioso: "Infeccioso",
  Gastrointestinal: "Gastrointestinal",
  "Gineco-obstétrico": "Gineco-obstétrico",
  "Pediátrico": "Pediatría",
  "Geriátrico": "Geriátrico",
  "Críticos y urgencias": "Urgencias y críticos",
};

type AreaTemplate = {
  summaryTail: string;
  clues: string[];
  redFlags: string[];
  priorities: string[];
  diagnostics: string[];
};

const TEMPLATE_BY_AREA: Record<MedicalArea, AreaTemplate> = {
  Cardiovascular: {
    summaryTail: "Cuadro cardiovascular que requiere valoración clínica y estratificación de riesgo.",
    clues: ["dolor torácico", "disnea", "palpitaciones", "fatiga de esfuerzo"],
    redFlags: ["hipotensión", "síncope", "isquemia aguda", "deterioro hemodinámico"],
    priorities: ["monitor cardíaco", "evaluar perfusión", "control hemodinámico", "escalamiento oportuno"],
    diagnostics: ["ECG", "troponinas", "ecocardiograma", "laboratorio básico"],
  },
  Respiratorio: {
    summaryTail: "Compromiso respiratorio con potencial deterioro ventilatorio y de oxigenación.",
    clues: ["disnea", "taquipnea", "tos", "desaturación"],
    redFlags: ["hipoxemia persistente", "fatiga respiratoria", "cianosis", "alteración de conciencia"],
    priorities: ["oxigenoterapia titulada", "vigilancia respiratoria", "control gasométrico", "alerta temprana de deterioro"],
    diagnostics: ["oximetría continua", "gasometría", "radiografía de tórax", "TAC según sospecha"],
  },
  "Neurológico": {
    summaryTail: "Síndrome neurológico que exige evaluación focal, temporalidad y riesgo de complicaciones.",
    clues: ["déficit focal", "cefalea", "alteración del sensorio", "convulsiones"],
    redFlags: ["deterioro neurológico rápido", "compromiso de conciencia", "inestabilidad autonómica", "déficit progresivo"],
    priorities: ["valoración neurológica seriada", "protección de vía aérea si precisa", "control hemodinámico", "escalamiento neurocrítico"],
    diagnostics: ["TAC/RM cerebral", "glucosa y electrolitos", "EEG/LCR según caso", "monitorización clínica frecuente"],
  },
  "Endocrino-metabólico": {
    summaryTail: "Desorden metabólico/hormonal con impacto sistémico y necesidad de corrección dirigida.",
    clues: ["alteración glucémica", "síntomas constitucionales", "debilidad", "trastorno hidroelectrolítico"],
    redFlags: ["compromiso neurológico", "arritmias", "deshidratación severa", "acidosis"],
    priorities: ["corrección metabólica protocolizada", "monitorización de electrolitos", "vigilancia hemodinámica", "educación para prevenir recurrencias"],
    diagnostics: ["perfil metabólico", "gasometría", "hormonas según sospecha", "monitor seriado de parámetros clave"],
  },
  Renal: {
    summaryTail: "Condición renal/urinaria con riesgo de deterioro de función y complicaciones sistémicas.",
    clues: ["alteración de diuresis", "dolor lumbar", "edema", "cambios en creatinina"],
    redFlags: ["anuria", "hiperkalemia", "sepsis urinaria", "sobrecarga hídrica severa"],
    priorities: ["monitor de diuresis", "control de volemia", "detección de complicaciones", "coordinación con nefrología/urología"],
    diagnostics: ["creatinina y electrolitos", "uroanálisis/urocultivo", "ecografía renal", "gasometría según gravedad"],
  },
  Infeccioso: {
    summaryTail: "Proceso infeccioso que requiere identificación del foco y control temprano de progresión.",
    clues: ["fiebre", "taquicardia", "respuesta inflamatoria", "deterioro funcional"],
    redFlags: ["sepsis", "hipotensión", "falla orgánica", "compromiso respiratorio o neurológico"],
    priorities: ["detección y control de foco", "antibioticoterapia/antimicrobianos oportunos", "monitor de sepsis", "medidas de aislamiento cuando aplica"],
    diagnostics: ["hemograma y PCR", "cultivos dirigidos", "lactato", "imágenes según foco"],
  },
  Gastrointestinal: {
    summaryTail: "Patología digestiva con posible progresión a compromiso hemodinámico o peritoneal.",
    clues: ["dolor abdominal", "náusea/vómito", "alteración del tránsito", "intolerancia oral"],
    redFlags: ["peritonismo", "sangrado digestivo", "inestabilidad hemodinámica", "sepsis abdominal"],
    priorities: ["reposo digestivo según indicación", "control del dolor", "balance hídrico", "vigilancia de complicaciones"],
    diagnostics: ["laboratorio metabólico", "ecografía/TAC abdominal", "hemograma", "endoscopia según cuadro"],
  },
  "Gineco-obstétrico": {
    summaryTail: "Evento gineco-obstétrico con enfoque en seguridad materna y, cuando aplica, bienestar fetal.",
    clues: ["dolor pélvico", "sangrado vaginal", "síntomas sistémicos", "cambios obstétricos"],
    redFlags: ["hemorragia activa", "hipotensión", "compromiso fetal", "sepsis obstétrica"],
    priorities: ["monitor materno-fetal", "cuantificar sangrado/estado clínico", "escalamiento obstétrico temprano", "acompañamiento y educación"],
    diagnostics: ["ecografía obstétrica/pélvica", "hemograma y coagulación", "grupo y factor", "marcadores de severidad"],
  },
  "Pediatría": {
    summaryTail: "Patología pediátrica con necesidad de valoración por edad, hidratación y riesgo respiratorio/infeccioso.",
    clues: ["fiebre", "cambios conductuales", "intolerancia oral", "compromiso respiratorio o gastrointestinal"],
    redFlags: ["deshidratación severa", "hipoxemia", "letargia", "sepsis pediátrica"],
    priorities: ["monitor pediátrico según edad", "soporte hídrico-respiratorio", "educación a cuidadores", "detección temprana de deterioro"],
    diagnostics: ["evaluación clínica pediátrica", "oximetría", "laboratorios dirigidos", "imagen según sospecha"],
  },
  "Geriátrico": {
    summaryTail: "Síndrome geriátrico con impacto funcional y alto riesgo de complicaciones por fragilidad.",
    clues: ["deterioro funcional", "cambios cognitivos", "caídas", "síntomas inespecíficos"],
    redFlags: ["delirium", "pérdida súbita de autonomía", "infección grave", "descompensación multiorgánica"],
    priorities: ["valoración geriátrica integral", "prevención de iatrogenia", "plan de seguridad y movilidad", "coordinación con red de apoyo"],
    diagnostics: ["tamizaje funcional/cognitivo", "laboratorio básico", "evaluación de comorbilidades", "revisión de medicación"],
  },
  "Urgencias y críticos": {
    summaryTail: "Emergencia clínica que exige estabilización inmediata y priorización ABCDE.",
    clues: ["inestabilidad hemodinámica", "compromiso respiratorio", "dolor intenso", "alteración del estado mental"],
    redFlags: ["choque", "falla multiorgánica", "deterioro rápido", "paro inminente"],
    priorities: ["ABC y reanimación inicial", "monitorización continua", "control de causa reversible", "escalamiento a unidad crítica"],
    diagnostics: ["gasometría y lactato", "monitor ECG", "POCUS/TAC según contexto", "laboratorio urgente"],
  },
};

type GeneratedBlueprint = {
  name: string;
  area: MedicalArea;
  urgency: MedicalUrgency;
  code: string;
  codeSystem?: MedicalCodeSystem;
};

const SUPPLEMENTAL_PATHOLOGY_BLUEPRINTS: GeneratedBlueprint[] = [
  { name: "Disección aórtica aguda", area: "Cardiovascular", urgency: "alta", code: "I71.0" },
  { name: "Miocardiopatía dilatada", area: "Cardiovascular", urgency: "media", code: "I42.0" },
  { name: "Miocardiopatía hipertrófica", area: "Cardiovascular", urgency: "media", code: "I42.2" },
  { name: "Taponamiento cardiaco", area: "Cardiovascular", urgency: "alta", code: "I31.4" },
  { name: "Síndrome de QT largo", area: "Cardiovascular", urgency: "media", code: "I45.8" },
  { name: "Tromboembolismo arterial periférico agudo", area: "Cardiovascular", urgency: "alta", code: "I74.9" },
  { name: "Fibrosis pulmonar idiopática", area: "Respiratorio", urgency: "media", code: "J84.1" },
  { name: "Neumonitis por hipersensibilidad", area: "Respiratorio", urgency: "media", code: "J67.9" },
  { name: "Derrame pleural maligno", area: "Respiratorio", urgency: "media", code: "J91" },
  { name: "Bronquiectasias infectadas", area: "Respiratorio", urgency: "media", code: "J47" },
  { name: "Hemoptisis moderada-severa", area: "Respiratorio", urgency: "alta", code: "R04.2" },
  { name: "Esclerosis múltiple en brote", area: "Neurológico", urgency: "media", code: "G35" },
  { name: "Crisis miasténica", area: "Neurológico", urgency: "alta", code: "G70.0" },
  { name: "Síndrome de Guillain-Barré", area: "Neurológico", urgency: "alta", code: "G61.0" },
  { name: "Hematoma subdural agudo", area: "Neurológico", urgency: "alta", code: "S06.5" },
  { name: "Hematoma epidural", area: "Neurológico", urgency: "alta", code: "S06.4" },
  { name: "Parkinson descompensado", area: "Neurológico", urgency: "media", code: "G20" },
  { name: "Hipercalcemia severa", area: "Endocrino-metabólico", urgency: "alta", code: "E83.52" },
  { name: "Hipocalcemia sintomática", area: "Endocrino-metabólico", urgency: "media", code: "E83.51" },
  { name: "Hipertrigliceridemia severa", area: "Endocrino-metabólico", urgency: "media", code: "E78.1" },
  { name: "Síndrome de realimentación", area: "Endocrino-metabólico", urgency: "alta", code: "E87.8" },
  { name: "Cetoacidosis alcohólica", area: "Endocrino-metabólico", urgency: "alta", code: "E87.2" },
  { name: "Acidosis tubular renal", area: "Renal", urgency: "media", code: "N25.8" },
  { name: "Nefritis intersticial aguda", area: "Renal", urgency: "media", code: "N10" },
  { name: "Rabdomiólisis con lesión renal", area: "Renal", urgency: "alta", code: "M62.82" },
  { name: "Uropatía obstructiva bilateral", area: "Renal", urgency: "alta", code: "N13.9" },
  { name: "Síndrome urémico hemolítico", area: "Renal", urgency: "alta", code: "D59.3" },
  { name: "Endometritis aguda", area: "Infeccioso", urgency: "media", code: "N71.0" },
  { name: "Osteomielitis aguda", area: "Infeccioso", urgency: "media", code: "M86.1" },
  { name: "Fascitis necrotizante", area: "Infeccioso", urgency: "alta", code: "M72.6" },
  { name: "Malaria grave", area: "Infeccioso", urgency: "alta", code: "B50.9" },
  { name: "Leptospirosis severa", area: "Infeccioso", urgency: "alta", code: "A27.9" },
  { name: "Meningoencefalitis tuberculosa", area: "Infeccioso", urgency: "alta", code: "A17.0" },
  { name: "Colangitis aguda", area: "Gastrointestinal", urgency: "alta", code: "K83.0" },
  { name: "Isquemia mesentérica aguda", area: "Gastrointestinal", urgency: "alta", code: "K55.0" },
  { name: "Diverticulitis complicada", area: "Gastrointestinal", urgency: "media", code: "K57.2" },
  { name: "Colitis ulcerosa en brote grave", area: "Gastrointestinal", urgency: "alta", code: "K51.9" },
  { name: "Enfermedad de Crohn activa", area: "Gastrointestinal", urgency: "media", code: "K50.9" },
  { name: "Hepatitis fulminante", area: "Gastrointestinal", urgency: "alta", code: "K72.0" },
  { name: "Síndrome HELLP", area: "Gineco-obstétrico", urgency: "alta", code: "O14.2" },
  { name: "Corioamnionitis", area: "Gineco-obstétrico", urgency: "alta", code: "O41.1" },
  { name: "Endometriosis profunda sintomática", area: "Gineco-obstétrico", urgency: "media", code: "N80.8" },
  { name: "Enfermedad inflamatoria pélvica", area: "Gineco-obstétrico", urgency: "media", code: "N73.9" },
  { name: "Mastitis puerperal", area: "Gineco-obstétrico", urgency: "media", code: "O91.2" },
  { name: "Enterocolitis necrosante neonatal", area: "Pediatría", urgency: "alta", code: "P77" },
  { name: "Laringomalacia sintomática", area: "Pediatría", urgency: "media", code: "Q31.5" },
  { name: "Coqueluche pediátrica", area: "Pediatría", urgency: "media", code: "A37.9" },
  { name: "Síndrome nefrótico pediátrico", area: "Pediatría", urgency: "media", code: "N04.9" },
  { name: "Síndrome compartimental agudo", area: "Urgencias y críticos", urgency: "alta", code: "T79.A" },
  { name: "Hipotermia accidental severa", area: "Urgencias y críticos", urgency: "alta", code: "T68" },
  { name: "Golpe de calor clásico", area: "Urgencias y críticos", urgency: "alta", code: "T67.0" },
  { name: "Ahogamiento no fatal", area: "Urgencias y críticos", urgency: "alta", code: "T75.1" },
];

const DEFAULT_CODE_BY_AREA: Record<MedicalArea, string> = {
  Cardiovascular: "I51.9",
  Respiratorio: "J98.9",
  "Neurológico": "G98",
  "Endocrino-metabólico": "E88.9",
  Renal: "N28.9",
  Infeccioso: "B99",
  Gastrointestinal: "K92.9",
  "Gineco-obstétrico": "O99.9",
  "Pediatría": "P29.9",
  "Geriátrico": "R69",
  "Urgencias y críticos": "R57.9",
};

const ICD10_RULES: Array<{ pattern: RegExp; code: string }> = [
  { pattern: /crisis hipertensiva/, code: "I16.9" },
  { pattern: /hipertension arterial|(^|[^a-z])hta([^a-z]|$)/, code: "I10" },
  { pattern: /sindrome coronario agudo|infarto/, code: "I21.9" },
  { pattern: /insuficiencia cardiaca|edema agudo de pulmon/, code: "I50.9" },
  { pattern: /fibrilacion auricular/, code: "I48.9" },
  { pattern: /arritmia supraventricular/, code: "I47.1" },
  { pattern: /endocarditis/, code: "I33.0" },
  { pattern: /miocarditis/, code: "I40.9" },
  { pattern: /pericarditis/, code: "I30.9" },
  { pattern: /diseccion aortica/, code: "I71.0" },
  { pattern: /taponamiento cardiaco/, code: "I31.4" },
  { pattern: /miocardiopatia dilatada/, code: "I42.0" },
  { pattern: /miocardiopatia hipertrofica/, code: "I42.2" },
  { pattern: /qt largo/, code: "I45.8" },
  { pattern: /valvulopatia aortica/, code: "I35.0" },
  { pattern: /trombosis venosa profunda/, code: "I82.4" },
  { pattern: /embolia pulmonar|tromboembolismo pulmonar/, code: "I26.9" },
  { pattern: /tromboembolismo arterial periferico/, code: "I74.9" },
  { pattern: /shock cardiogenico/, code: "R57.0" },
  { pattern: /insuficiencia respiratoria aguda/, code: "J96.0" },
  { pattern: /sdra|distres respiratorio agudo/, code: "J80" },
  { pattern: /neumotorax/, code: "J93.9" },
  { pattern: /derrame pleural maligno/, code: "J91" },
  { pattern: /derrame pleural/, code: "J90" },
  { pattern: /tuberculosis pulmonar/, code: "A15.0" },
  { pattern: /asma|crisis asmatica pediatrica/, code: "J45.9" },
  { pattern: /estatus asmatico|estado de mal asmatico|exacerbacion asmatica grave/, code: "J46" },
  { pattern: /epoc/, code: "J44.9" },
  { pattern: /neumonia/, code: "J18.9" },
  { pattern: /apnea obstructiva del sueno/, code: "G47.3" },
  { pattern: /bronquiectasias/, code: "J47" },
  { pattern: /fibrosis pulmonar/, code: "J84.1" },
  { pattern: /neumonitis por hipersensibilidad/, code: "J67.9" },
  { pattern: /hemoptisis/, code: "R04.2" },
  { pattern: /crup|laringotraqueitis/, code: "J05.0" },
  { pattern: /bronquiolitis/, code: "J21.9" },
  { pattern: /acv hemorragico/, code: "I61.9" },
  { pattern: /acv|accidente cerebrovascular|ictus/, code: "I63.9" },
  { pattern: /hemorragia subaracnoidea/, code: "I60.9" },
  { pattern: /hematoma subdural/, code: "S06.5" },
  { pattern: /hematoma epidural/, code: "S06.4" },
  { pattern: /trauma craneoencefalico|traumatismo craneoencefalico/, code: "S06.9" },
  { pattern: /epilepsia/, code: "G40.9" },
  { pattern: /estatus epileptico/, code: "G41.9" },
  { pattern: /convulsion febril/, code: "R56.0" },
  { pattern: /meningoencefalitis tuberculosa/, code: "A17.0" },
  { pattern: /meningitis/, code: "G00.9" },
  { pattern: /encefalitis/, code: "G04.9" },
  { pattern: /delirium|sindrome confusional/, code: "F05" },
  { pattern: /migra/, code: "G43.9" },
  { pattern: /neuropatia periferica diabetica/, code: "E11.4" },
  { pattern: /esclerosis multiple/, code: "G35" },
  { pattern: /miasten/, code: "G70.0" },
  { pattern: /guillain/, code: "G61.0" },
  { pattern: /parkinson/, code: "G20" },
  { pattern: /demencia tipo alzheimer|alzheimer/, code: "G30.9" },
  { pattern: /demencia vascular/, code: "F01.9" },
  { pattern: /caidas recurrentes/, code: "R29.6" },
  { pattern: /diabetes mellitus tipo 2|(^|[^a-z])dm2([^a-z]|$)/, code: "E11.9" },
  { pattern: /cetoacidosis diabetica|(^|[^a-z])cetoacidosis([^a-z]|$)/, code: "E10.1" },
  { pattern: /estado hiperosmolar/, code: "E11.0" },
  { pattern: /hipotiroidismo/, code: "E03.9" },
  { pattern: /hipertiroidismo/, code: "E05.9" },
  { pattern: /tormenta tiroidea/, code: "E05.5" },
  { pattern: /insuficiencia suprarrenal/, code: "E27.2" },
  { pattern: /hipoglucemia severa/, code: "E16.2" },
  { pattern: /hiponatremia/, code: "E87.1" },
  { pattern: /hiperpotasemia/, code: "E87.5" },
  { pattern: /hipercalcemia/, code: "E83.52" },
  { pattern: /hipocalcemia/, code: "E83.51" },
  { pattern: /hipertrigliceridemia/, code: "E78.1" },
  { pattern: /sindrome metabolico/, code: "E88.81" },
  { pattern: /obesidad/, code: "E66.9" },
  { pattern: /diabetes gestacional/, code: "O24.4" },
  { pattern: /realimentacion/, code: "E87.8" },
  { pattern: /cetoacidosis alcoholica/, code: "E87.2" },
  { pattern: /lesion renal aguda|(^|[^a-z])ira([^a-z]|$)/, code: "N17.9" },
  { pattern: /enfermedad renal cronica|(^|[^a-z])erc([^a-z]|$)/, code: "N18.9" },
  { pattern: /pielonefritis/, code: "N10" },
  { pattern: /litiasis renal/, code: "N20.0" },
  { pattern: /glomerulonefritis/, code: "N00.9" },
  { pattern: /sindrome nefrotico/, code: "N04.9" },
  { pattern: /retencion urinaria aguda/, code: "R33" },
  { pattern: /sepsis urinaria/, code: "A41.9" },
  { pattern: /hematuria macroscopic|hematuria macroscopica/, code: "R31.0" },
  { pattern: /incontinencia urinaria/, code: "R32" },
  { pattern: /hiperplasia prostatica/, code: "N40.1" },
  { pattern: /acidosis tubular renal/, code: "N25.8" },
  { pattern: /nefritis intersticial/, code: "N10" },
  { pattern: /uropatia obstructiva/, code: "N13.9" },
  { pattern: /rabdomiolisis/, code: "M62.82" },
  { pattern: /sindrome uremico hemolitico/, code: "D59.3" },
  { pattern: /sepsis neonatal/, code: "P36.9" },
  { pattern: /shock septico/, code: "R65.2" },
  { pattern: /sepsis/, code: "A41.9" },
  { pattern: /dengue/, code: "A97.9" },
  { pattern: /chikungunya/, code: "A92.0" },
  { pattern: /influenza/, code: "J10.1" },
  { pattern: /covid/, code: "U07.1" },
  { pattern: /celulitis/, code: "L03.9" },
  { pattern: /infeccion de piel y tejidos blandos/, code: "L08.9" },
  { pattern: /fiebre de origen desconocido/, code: "R50.9" },
  { pattern: /neutropenia febril/, code: "D70.9" },
  { pattern: /vih/, code: "B24" },
  { pattern: /infeccion intraabdominal|sepsis de foco abdominal|peritonitis secundaria/, code: "K65.9" },
  { pattern: /hepatitis fulminante/, code: "K72.0" },
  { pattern: /hepatitis aguda/, code: "B17.9" },
  { pattern: /endometritis/, code: "N71.0" },
  { pattern: /osteomielitis/, code: "M86.1" },
  { pattern: /fascitis necrotizante/, code: "M72.6" },
  { pattern: /malaria/, code: "B50.9" },
  { pattern: /leptospirosis/, code: "A27.9" },
  { pattern: /coqueluche/, code: "A37.9" },
  { pattern: /gastroenteritis|diarrea aguda pediatrica/, code: "A09" },
  { pattern: /apendicitis/, code: "K35.9" },
  { pattern: /pancreatitis/, code: "K85.9" },
  { pattern: /colecistitis/, code: "K81.0" },
  { pattern: /hemorragia digestiva alta|hemorragia digestiva baja/, code: "K92.2" },
  { pattern: /obstruccion intestinal/, code: "K56.6" },
  { pattern: /cirrosis/, code: "K74.6" },
  { pattern: /colangitis/, code: "K83.0" },
  { pattern: /isquemia mesenterica/, code: "K55.0" },
  { pattern: /diverticulitis/, code: "K57.2" },
  { pattern: /colitis ulcerosa/, code: "K51.9" },
  { pattern: /crohn/, code: "K50.9" },
  { pattern: /malnutricion pediatrica/, code: "E46" },
  { pattern: /dolor cronico osteoarticular/, code: "M25.5" },
  { pattern: /embarazo ectopico/, code: "O00.9" },
  { pattern: /amenaza de aborto/, code: "O20.0" },
  { pattern: /aborto incompleto/, code: "O03.4" },
  { pattern: /preeclampsia/, code: "O14.9" },
  { pattern: /eclampsia/, code: "O15.9" },
  { pattern: /sindrome hellp/, code: "O14.2" },
  { pattern: /hemorragia posparto/, code: "O72.1" },
  { pattern: /amenaza de parto pretermino|trabajo de parto pretermino/, code: "O60.0" },
  { pattern: /ruptura prematura de membranas/, code: "O42.9" },
  { pattern: /placenta previa/, code: "O44.1" },
  { pattern: /desprendimiento prematuro de placenta/, code: "O45.9" },
  { pattern: /infeccion puerperal|sepsis puerperal/, code: "O85" },
  { pattern: /infeccion urinaria en embarazo/, code: "O23.4" },
  { pattern: /corioamnionitis/, code: "O41.1" },
  { pattern: /endometriosis/, code: "N80.9" },
  { pattern: /enfermedad inflamatoria pelvica/, code: "N73.9" },
  { pattern: /mastitis puerperal/, code: "O91.2" },
  { pattern: /enterocolitis necrosante/, code: "P77" },
  { pattern: /ictericia neonatal/, code: "P59.9" },
  { pattern: /otitis media aguda/, code: "H66.9" },
  { pattern: /faringoamigdalitis/, code: "J03.9" },
  { pattern: /anemia ferropenica pediatrica/, code: "D50.9" },
  { pattern: /sindrome nefrotico pediatrico/, code: "N04.9" },
  { pattern: /laringomalacia/, code: "Q31.5" },
  { pattern: /anafilaxia/, code: "T78.2" },
  { pattern: /paro cardiorrespiratorio|reanimacion post paro|post-rce/, code: "I46.9" },
  { pattern: /sangrado masivo/, code: "R58" },
  { pattern: /intoxicacion aguda por farmacos|intoxicacion aguda/, code: "T50.9" },
  { pattern: /quemaduras/, code: "T30.0" },
  { pattern: /politrauma/, code: "T07" },
  { pattern: /trauma toracico/, code: "S29.9" },
  { pattern: /shock hipovolemico/, code: "R57.1" },
  { pattern: /sindrome compartimental/, code: "T79.A" },
  { pattern: /hipotermia accidental/, code: "T68" },
  { pattern: /golpe de calor/, code: "T67.0" },
  { pattern: /ahogamiento/, code: "T75.1" },
  { pattern: /fragilidad geriatrica/, code: "R54" },
  { pattern: /ulceras por presion/, code: "L89.9" },
  { pattern: /polifarmacia/, code: "Z79.899" },
];

function normalizeLite(value: string) {
  return String(value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function slugify(value: string) {
  return normalizeLite(value).replace(/\s+/g, "-");
}

function inferIcd10Code(seed: MedicalPathologySeed) {
  const text = normalizeLite(`${seed.id} ${seed.name}`);
  for (const rule of ICD10_RULES) {
    if (rule.pattern.test(text)) return rule.code;
  }
  return DEFAULT_CODE_BY_AREA[seed.area];
}

function buildTemplatePathology(seed: {
  id?: string;
  name: string;
  area: MedicalArea;
  urgency: MedicalUrgency;
  code?: string;
  codeSystem?: MedicalCodeSystem;
}): MedicalPathologySeed {
  const tpl = TEMPLATE_BY_AREA[seed.area];
  return {
    id: seed.id ?? slugify(seed.name),
    name: seed.name,
    area: seed.area,
    urgency: seed.urgency,
    code: seed.code,
    codeSystem: seed.codeSystem ?? "CIE-10",
    summary: `${seed.name}. ${tpl.summaryTail}`,
    clinical_clues: [...tpl.clues],
    red_flags: [...tpl.redFlags],
    nursing_priorities: [...tpl.priorities],
    diagnostic_support: [...tpl.diagnostics],
  };
}

function mapCaseCatalogToPathologySeed() {
  const existingNames = new Set(
    [...BASE_MEDICAL_PATHOLOGY_LIBRARY, ...EXTRA_MEDICAL_PATHOLOGY_LIBRARY].map((item) =>
      normalizeLite(item.name)
    )
  );

  return MEDICAL_CASE_CATALOG.filter(
    (item) => !existingNames.has(normalizeLite(item.title))
  ).map((item) =>
    buildTemplatePathology({
      id: item.id,
      name: item.title,
      area: CASE_AREA_TO_MEDICAL_AREA[item.area],
      urgency: item.urgency,
    })
  );
}

function mapSupplementalToPathologySeed() {
  return SUPPLEMENTAL_PATHOLOGY_BLUEPRINTS.map((item) =>
    buildTemplatePathology({
      id: slugify(item.name),
      name: item.name,
      area: item.area,
      urgency: item.urgency,
      code: item.code,
      codeSystem: item.codeSystem ?? "CIE-10",
    })
  );
}

function buildMedicalPathologyLibrary() {
  const combined: MedicalPathologySeed[] = [
    ...BASE_MEDICAL_PATHOLOGY_LIBRARY,
    ...EXTRA_MEDICAL_PATHOLOGY_LIBRARY,
    ...mapCaseCatalogToPathologySeed(),
    ...mapSupplementalToPathologySeed(),
  ];

  const byId = new Set<string>();
  const byName = new Set<string>();
  const out: MedicalPathology[] = [];

  for (const seed of combined) {
    const normalizedName = normalizeLite(seed.name);
    if (byName.has(normalizedName)) continue;

    const baseId = seed.id || slugify(seed.name);
    let safeId = baseId;
    let suffix = 2;
    while (byId.has(safeId)) {
      safeId = `${baseId}-${suffix}`;
      suffix += 1;
    }

    byId.add(safeId);
    byName.add(normalizedName);

    out.push({
      ...seed,
      id: safeId,
      codeSystem: seed.codeSystem ?? "CIE-10",
      code: (seed.code ?? inferIcd10Code(seed)).trim(),
    });
  }

  if (out.length < TARGET_MEDICAL_PATHOLOGY_COUNT) {
    const rotations = MEDICAL_AREAS.filter((x) => x !== "Geriátrico");
    let fallbackIndex = 1;
    while (out.length < TARGET_MEDICAL_PATHOLOGY_COUNT) {
      const area = rotations[(fallbackIndex - 1) % rotations.length];
      const filler = buildTemplatePathology({
        name: `Patología clínica complementaria ${fallbackIndex}`,
        area,
        urgency: fallbackIndex % 3 === 0 ? "alta" : fallbackIndex % 2 === 0 ? "media" : "baja",
      });
      const fillerName = normalizeLite(filler.name);
      if (!byName.has(fillerName)) {
        const fillerId = `${filler.id}-${fallbackIndex}`;
        byName.add(fillerName);
        byId.add(fillerId);
        out.push({
          ...filler,
          id: fillerId,
          codeSystem: "CIE-10",
          code: inferIcd10Code(filler),
        });
      }
      fallbackIndex += 1;
    }
  }

  return out.slice(0, TARGET_MEDICAL_PATHOLOGY_COUNT);
}

export const MEDICAL_PATHOLOGY_LIBRARY: MedicalPathology[] = buildMedicalPathologyLibrary();
