import {
  type WoundCaseData,
  type WoundDifficulty,
  WOUND_COMPETENCY_LABELS,
} from "@/src/lib/wound-care/types";

export function woundDifficultyLabel(difficulty: WoundDifficulty) {
  if (difficulty === "basic") return "Básico";
  if (difficulty === "intermediate") return "Intermedio";
  return "Avanzado";
}

export const WOUND_MODULE_COMPETENCIES = Object.entries(WOUND_COMPETENCY_LABELS).map(([key, label]) => ({
  key,
  label,
}));

const MEDETEC_SOURCE = "Base clínica Medetec · uso educativo con overlay didáctico";

export const WOUND_LPP_CASES: WoundCaseData[] = [
  {
    id: "lpp-risk-high",
    name: "Caso 1: Riesgo alto sin lesión avanzada",
    difficulty: "basic",
    summary: "Paciente inmovilizado con humedad frecuente y eritema persistente en sacro. Prioriza riesgo, prevención y detección temprana.",
    learningObjective: "Reconocer alto riesgo, diferenciar daño inicial y activar medidas preventivas completas.",
    estimatedMinutes: 12,
    patient: {
      age: 79,
      sex: "Femenino",
      context: "Hospitalización por neumonía comunitaria, 5 días en cama, tos productiva y debilidad marcada.",
      relevantHistory: ["HTA", "Dependencia parcial para ABVD", "Incontinencia urinaria nocturna"],
      mobility: "Necesita ayuda de dos personas para movilizarse.",
      nutrition: "Ingesta oral disminuida, albúmina limítrofe.",
      hydration: "Mucosas ligeramente secas; aporte intravenoso en curso.",
      continence: "Humedad perineal frecuente por incontinencia.",
      perfusion: "Llenado capilar lento, piel fría distal.",
      timeInBed: "Más de 18 horas al día en decúbito.",
      devices: ["Sonda vesical intermitente", "Mascarilla simple de oxígeno"],
      pain: "Dolor leve al girar sobre sacro.",
      vitals: {
        bloodPressure: "132/76 mmHg",
        heartRate: "96 lpm",
        respiratoryRate: "22 rpm",
        temperature: "37.2 °C",
        oxygenSaturation: "94%",
      },
      braden: {
        score: 11,
        interpretation: "Riesgo alto de lesión por presión.",
      },
      caseGoal: "Determinar riesgo, describir hallazgos tempranos y montar un plan preventivo antes de que la lesión progrese.",
    },
    wound: {
      location: "Sacro",
      bodySite: "sacrum",
      locationLabel: "Región sacra",
      lengthCm: 2.8,
      widthCm: 2.1,
      depthCm: 0,
      edges: "Íntegros y definidos",
      tissue: "Piel intacta con eritema no blanqueable",
      exudate: "Nulo",
      odor: "Sin olor",
      periwoundSkin: "Eritematosa",
      pain: "Dolor leve",
      infectionSigns: [],
      hasSlough: false,
      hasNecrosis: false,
      stage: "Estadio I",
      hotspots: [
        { id: "center", label: "Centro", description: "Eritema persistente sobre prominencia ósea, sin pérdida de continuidad.", x: 50, y: 44 },
        { id: "edge", label: "Borde", description: "Bordes bien delimitados, sin maceración significativa.", x: 66, y: 51 },
        { id: "skin", label: "Perilesión", description: "Piel húmeda y frágil por exposición repetida a humedad.", x: 34, y: 55 },
      ],
      differentialNote: "Debes diferenciar entre presión temprana y lesión por humedad; el patrón sobre prominencia ósea y el eritema no blanqueable orientan a LPP estadio I.",
      visual: {
        imageSrc: "/medical-assets/wound-care/lpp/medetec-pressure-ulcer-sacrum-healing.jpg",
        imageAlt: "Base clínica de región sacra suavizada para entrenamiento en lesión por presión de riesgo alto.",
        imageSourceLabel: MEDETEC_SOURCE,
        objectPosition: "center center",
        photoOpacity: 0.24,
        overlayTone: "risk",
        focus: { x: 49, y: 51, width: 42, height: 30, rotation: -6 },
        notes: [
          "Se suaviza la foto real para priorizar valoración del riesgo y eritema temprano.",
          "El overlay reemplaza profundidad visible por un hallazgo superficial didáctico.",
        ],
      },
    },
    expected: {
      reviewedDomains: ["mobility", "nutrition", "hydration", "continence", "perfusion", "timeInBed", "devices", "pain", "braden"],
      riskFactors: ["immobility", "malnutrition", "moisture", "poor-perfusion", "low-braden"],
      priorityAlerts: ["moisture-damage"],
      materialIds: ["hand-hygiene", "clean-gloves", "gauze", "saline", "skin-barrier", "hydrocolloid", "waste", "positioning-aid"],
      inappropriateMaterialIds: ["alcohol", "dry-cotton", "alginate"],
      procedureSequence: [
        "hand-hygiene-start",
        "explain-patient",
        "prepare-position",
        "remove-old-dressing",
        "reassess-on-removal",
        "cleanse",
        "protect-periwound",
        "apply-cover",
        "secure-dressing",
        "dispose-waste",
        "hand-hygiene-end",
        "document-care",
      ],
      preventionIds: ["turning-schedule", "moisture-management", "nutrition-support", "pressure-relief", "caregiver-education", "reassessment"],
      documentationChecklist: ["location", "classification", "woundBed", "odor", "pain", "intervention", "dressing", "followUpPlan"],
      classificationKeywords: ["eritema", "no blanqueable", "piel intacta", "prominencia ósea"],
    },
    education: {
      fundamentals: [
        "La valoración del riesgo precede a la curación y determina la intensidad de la prevención.",
        "La LPP estadio I mantiene piel intacta; no hay pérdida de espesor ni cavidad.",
      ],
      prevention: [
        "Reposicionamiento programado y control de humedad son medidas centrales.",
        "La escala de Braden orienta riesgo, pero no reemplaza la valoración clínica directa.",
      ],
      differentiation:
        "Una lesión por humedad suele ser más difusa y no necesariamente coincide con una prominencia ósea; aquí el contexto y la localización favorecen LPP temprana.",
    },
    outcome: {
      improvement: "El eritema disminuye y el paciente mantiene integridad cutánea gracias a reposicionamiento y control de humedad.",
      stable: "La zona no progresa, pero persiste riesgo alto que exige vigilancia continua.",
      worsening: "La lesión evoluciona a pérdida parcial de espesor por mantenimiento de presión y humedad.",
    },
  },
  {
    id: "lpp-stage-1-heel",
    name: "Caso 2: LPP estadio I",
    difficulty: "basic",
    summary: "Talón derecho con eritema no blanqueable en paciente con inmovilidad postquirúrgica.",
    learningObjective: "Identificar LPP estadio I en talón y priorizar descarga de presión.",
    estimatedMinutes: 12,
    patient: {
      age: 67,
      sex: "Masculino",
      context: "Postoperatorio de fractura de cadera, limitado para apoyar y movilizar extremidad inferior.",
      relevantHistory: ["Diabetes mellitus tipo 2", "Neuropatía periférica leve"],
      mobility: "Reposo en cama con movilización asistida.",
      nutrition: "Acepta dieta blanda, apetito regular.",
      hydration: "Hidratación adecuada por vía oral.",
      continence: "Continente.",
      perfusion: "Perfusión distal disminuida en miembros inferiores.",
      timeInBed: "16 horas al día.",
      devices: ["Bota inmovilizadora intermitente"],
      pain: "Dolor moderado en cadera; talón sensible a la presión.",
      vitals: {
        bloodPressure: "128/74 mmHg",
        heartRate: "88 lpm",
        respiratoryRate: "18 rpm",
        temperature: "36.8 °C",
        oxygenSaturation: "97%",
      },
      braden: {
        score: 13,
        interpretation: "Riesgo moderado-alto.",
      },
      caseGoal: "Evitar progresión de la lesión en talón y documentar correctamente hallazgos iniciales.",
    },
    wound: {
      location: "Talón derecho",
      bodySite: "heel",
      locationLabel: "Talón derecho",
      lengthCm: 2.2,
      widthCm: 2,
      depthCm: 0,
      edges: "Íntegros y definidos",
      tissue: "Piel intacta con eritema no blanqueable",
      exudate: "Nulo",
      odor: "Sin olor",
      periwoundSkin: "Íntegra",
      pain: "Dolor moderado",
      infectionSigns: [],
      hasSlough: false,
      hasNecrosis: false,
      stage: "Estadio I",
      hotspots: [
        { id: "center", label: "Centro", description: "Área enrojecida persistente sin pérdida de piel.", x: 52, y: 58 },
        { id: "pressure", label: "Presión", description: "Talón sometido a carga prolongada y fricción con superficie de apoyo.", x: 66, y: 64 },
        { id: "skin", label: "Perilesión", description: "Piel seca, sin maceración ni exudado.", x: 38, y: 54 },
      ],
      differentialNote: "El talón exige diferenciar isquemia, fricción y presión sostenida; aquí la piel sigue intacta y el hallazgo clave es el eritema no blanqueable.",
      visual: {
        imageSrc: "/medical-assets/wound-care/lpp/medetec-pressure-ulcer-heel.jpg",
        imageAlt: "Base clínica de talón suavizada con overlay para LPP estadio I.",
        imageSourceLabel: MEDETEC_SOURCE,
        objectPosition: "center center",
        photoOpacity: 0.28,
        overlayTone: "stage-1",
        focus: { x: 52, y: 59, width: 34, height: 24, rotation: 8 },
        notes: [
          "El overlay didáctico oculta la pérdida de continuidad de la foto base para representar estadio I.",
          "La lectura clínica se centra en eritema no blanqueable y descarga de talón.",
        ],
      },
    },
    expected: {
      reviewedDomains: ["mobility", "nutrition", "perfusion", "timeInBed", "devices", "pain", "braden"],
      riskFactors: ["immobility", "poor-perfusion", "device-pressure", "diabetes", "low-braden"],
      priorityAlerts: ["deep-loss"],
      materialIds: ["hand-hygiene", "clean-gloves", "gauze", "saline", "skin-barrier", "hydrocolloid", "waste", "positioning-aid"],
      inappropriateMaterialIds: ["alcohol", "dry-cotton", "alginate"],
      procedureSequence: [
        "hand-hygiene-start",
        "explain-patient",
        "prepare-position",
        "remove-old-dressing",
        "reassess-on-removal",
        "cleanse",
        "protect-periwound",
        "apply-cover",
        "secure-dressing",
        "dispose-waste",
        "hand-hygiene-end",
        "document-care",
      ],
      preventionIds: ["turning-schedule", "pressure-relief", "pain-control", "reassessment"],
      documentationChecklist: ["location", "classification", "woundBed", "odor", "pain", "intervention", "dressing", "followUpPlan"],
      classificationKeywords: ["talón", "piel intacta", "eritema", "no blanqueable"],
    },
    education: {
      fundamentals: [
        "El talón es una prominencia ósea crítica y requiere descarga temprana.",
        "El estadio I no presenta ampolla ni pérdida de dermis.",
      ],
      prevention: [
        "Flotar talones y controlar presión de dispositivos evita progresión.",
        "En pacientes con neuropatía, el dolor puede subestimar el daño real.",
      ],
      differentiation:
        "La lesión tisular profunda puede verse violácea o con ampolla hemática; aquí el color es eritematoso y la piel se mantiene íntegra.",
    },
    outcome: {
      improvement: "El talón pierde eritema y responde a descarga continua.",
      stable: "La lesión no progresa, pero exige vigilancia por neuropatía y perfusión deficiente.",
      worsening: "Aparece pérdida parcial de espesor por descarga insuficiente.",
    },
  },
  {
    id: "lpp-stage-2",
    name: "Caso 3: LPP estadio II",
    difficulty: "intermediate",
    summary: "Lesión superficial en sacro con pérdida parcial de espesor y exudado escaso.",
    learningObjective: "Valorar dimensiones, clasificar correctamente y seleccionar una cobertura básica.",
    estimatedMinutes: 14,
    patient: {
      age: 72,
      sex: "Femenino",
      context: "Internación por EPOC reagudizado con periodos prolongados en cama.",
      relevantHistory: ["Obesidad", "Incontinencia urinaria funcional"],
      mobility: "Se moviliza poco por disnea.",
      nutrition: "Aporte calórico irregular, proteína insuficiente.",
      hydration: "Aceptable con apoyo IV.",
      continence: "Humedad recurrente en región sacra.",
      perfusion: "Adecuada, sin datos de shock.",
      timeInBed: "Mayor parte del día en decúbito dorsal.",
      devices: ["Cánula nasal", "Pañal absorbente"],
      pain: "Dolor moderado al contacto.",
      vitals: {
        bloodPressure: "118/68 mmHg",
        heartRate: "92 lpm",
        respiratoryRate: "24 rpm",
        temperature: "36.9 °C",
        oxygenSaturation: "92%",
      },
      braden: {
        score: 12,
        interpretation: "Riesgo alto.",
      },
      caseGoal: "Completar valoración local y escoger una curación compatible con lesión superficial.",
    },
    wound: {
      location: "Sacro",
      bodySite: "sacrum",
      locationLabel: "Sacro",
      lengthCm: 3.4,
      widthCm: 2.6,
      depthCm: 0.2,
      edges: "Macerados",
      tissue: "Lecho rosado o rojo",
      exudate: "Escaso",
      odor: "Sin olor",
      periwoundSkin: "Macerada",
      pain: "Dolor moderado",
      infectionSigns: [],
      hasSlough: false,
      hasNecrosis: false,
      stage: "Estadio II",
      hotspots: [
        { id: "bed", label: "Lecho", description: "Pérdida parcial de piel con lecho rosado y húmedo.", x: 50, y: 51 },
        { id: "edge", label: "Borde", description: "Maceración leve por humedad cercana.", x: 65, y: 48 },
        { id: "skin", label: "Perilesión", description: "La piel circundante está húmeda y vulnerable.", x: 38, y: 58 },
      ],
      differentialNote: "El estadio II muestra pérdida parcial del espesor con lecho visible, sin esfacelos que oculten profundidad.",
      visual: {
        imageSrc: "/medical-assets/wound-care/lpp/medetec-pressure-ulcer-sacrum-healing.jpg",
        imageAlt: "Base clínica de región sacra suavizada con overlay para LPP estadio II.",
        imageSourceLabel: MEDETEC_SOURCE,
        objectPosition: "center center",
        photoOpacity: 0.34,
        overlayTone: "stage-2",
        focus: { x: 49, y: 52, width: 40, height: 30, rotation: -4 },
        notes: [
          "La foto clínica aporta textura y contorno anatómico.",
          "El overlay didáctico reconstruye una pérdida parcial superficial acorde al estadio II.",
        ],
      },
    },
    expected: {
      reviewedDomains: ["mobility", "nutrition", "hydration", "continence", "timeInBed", "pain", "braden"],
      riskFactors: ["immobility", "malnutrition", "moisture", "low-braden"],
      priorityAlerts: ["moisture-damage"],
      materialIds: ["hand-hygiene", "clean-gloves", "gauze", "saline", "skin-barrier", "hydrocolloid", "waste", "adhesive-mesh"],
      inappropriateMaterialIds: ["alcohol", "dry-cotton", "alginate"],
      procedureSequence: [
        "hand-hygiene-start",
        "explain-patient",
        "prepare-position",
        "remove-old-dressing",
        "reassess-on-removal",
        "cleanse",
        "protect-periwound",
        "apply-cover",
        "secure-dressing",
        "dispose-waste",
        "hand-hygiene-end",
        "document-care",
      ],
      preventionIds: ["turning-schedule", "moisture-management", "pressure-relief", "pain-control", "reassessment"],
      documentationChecklist: ["location", "classification", "woundBed", "exudate", "odor", "pain", "intervention", "dressing", "followUpPlan"],
      classificationKeywords: ["pérdida parcial", "lecho rosado", "superficial"],
    },
    education: {
      fundamentals: [
        "La profundidad superficial y el lecho visible descartan estadio III.",
        "La maceración perilesional exige barrera protectora y control de humedad.",
      ],
      prevention: [
        "El manejo de humedad es tan importante como la cobertura local.",
        "La reevaluación temprana detecta progresión cuando el paciente sigue inmóvil.",
      ],
      differentiation:
        "No confundas estadio II con ampollas por fricción aislada: aquí la localización, el contexto y la presión sostenida orientan a LPP.",
    },
    outcome: {
      improvement: "Se conserva un lecho rosado y disminuye la maceración.",
      stable: "La herida mantiene exudado escaso sin progresión evidente.",
      worsening: "Aumenta profundidad por persistencia de humedad y presión.",
    },
  },
  {
    id: "lpp-stage-3-exudative",
    name: "Caso 4: LPP estadio III con exudado moderado",
    difficulty: "advanced",
    summary: "Lesión sacra profunda con pérdida total de piel, granulación y esfacelos. Requiere curación integral.",
    learningObjective: "Elegir cobertura adecuada para exudado moderado, secuencia segura y plan preventivo completo.",
    estimatedMinutes: 18,
    patient: {
      age: 84,
      sex: "Masculino",
      context: "Estadía prolongada en UCI ya superada; ahora en hospitalización general con debilidad extrema.",
      relevantHistory: ["Desnutrición proteica", "Anemia", "Dependencia total"],
      mobility: "No se reposiciona sin asistencia completa.",
      nutrition: "Requerimientos altos, apoyo enteral parcial.",
      hydration: "Balance hídrico vigilado.",
      continence: "Incontinencia urinaria y fecal ocasional.",
      perfusion: "Perfusión periférica disminuida, edema leve.",
      timeInBed: "Más de 20 horas al día.",
      devices: ["Sonda vesical", "Colchón terapéutico"],
      pain: "Dolor moderado durante la curación.",
      vitals: {
        bloodPressure: "110/62 mmHg",
        heartRate: "98 lpm",
        respiratoryRate: "20 rpm",
        temperature: "37.4 °C",
        oxygenSaturation: "95%",
      },
      braden: {
        score: 9,
        interpretation: "Riesgo muy alto.",
      },
      caseGoal: "Manejar una LPP estadio III con exudado moderado sin omitir medidas complementarias.",
    },
    wound: {
      location: "Sacro",
      bodySite: "sacrum",
      locationLabel: "Sacro",
      lengthCm: 5.8,
      widthCm: 4.6,
      depthCm: 1.2,
      edges: "Irregulares",
      tissue: "Granulación con esfacelos",
      exudate: "Moderado",
      odor: "Leve",
      periwoundSkin: "Frágil",
      pain: "Dolor moderado",
      infectionSigns: ["Eritema progresivo", "Olor persistente"],
      hasSlough: true,
      hasNecrosis: false,
      stage: "Estadio III",
      hotspots: [
        { id: "bed", label: "Lecho", description: "Pérdida total de piel con tejido de granulación y zonas de esfacelo.", x: 51, y: 50 },
        { id: "depth", label: "Profundidad", description: "Se aprecia cavidad superficial compatible con estadio III.", x: 61, y: 53 },
        { id: "skin", label: "Perilesión", description: "Piel frágil con riesgo de maceración por exudado.", x: 37, y: 45 },
      ],
      differentialNote: "Hay pérdida total de piel con tejido subcutáneo visible, pero sin exposición de fascia, tendón ni hueso, compatible con estadio III.",
      visual: {
        imageSrc: "/medical-assets/wound-care/lpp/medetec-pressure-ulcer-sacrum-deep-sloughy.jpg",
        imageAlt: "Base clínica de lesión sacra profunda con overlay didáctico para LPP estadio III.",
        imageSourceLabel: MEDETEC_SOURCE,
        objectPosition: "center center",
        photoOpacity: 0.72,
        overlayTone: "stage-3",
        focus: { x: 50, y: 49, width: 48, height: 36, rotation: -2 },
        notes: [
          "Se mantiene mayor visibilidad de la base clínica por tratarse de una lesión profunda.",
          "El overlay resalta granulación, exudado moderado y piel perilesional frágil.",
        ],
      },
    },
    expected: {
      reviewedDomains: ["mobility", "nutrition", "hydration", "continence", "perfusion", "timeInBed", "devices", "pain", "braden"],
      riskFactors: ["immobility", "malnutrition", "moisture", "poor-perfusion", "low-braden"],
      priorityAlerts: ["infection", "pain-rise"],
      materialIds: ["hand-hygiene", "clean-gloves", "gauze", "saline", "skin-barrier", "foam-dressing", "waste", "positioning-aid", "adhesive-mesh"],
      inappropriateMaterialIds: ["alcohol", "dry-cotton", "hydrocolloid"],
      procedureSequence: [
        "hand-hygiene-start",
        "explain-patient",
        "prepare-position",
        "remove-old-dressing",
        "reassess-on-removal",
        "cleanse",
        "protect-periwound",
        "apply-cover",
        "secure-dressing",
        "dispose-waste",
        "hand-hygiene-end",
        "document-care",
      ],
      preventionIds: ["turning-schedule", "moisture-management", "nutrition-support", "pressure-relief", "pain-control", "infection-watch", "reassessment", "caregiver-education"],
      documentationChecklist: ["location", "classification", "woundBed", "exudate", "odor", "pain", "intervention", "dressing", "patientResponse", "followUpPlan"],
      classificationKeywords: ["pérdida total", "subcutáneo", "granulación", "sin hueso expuesto"],
    },
    education: {
      fundamentals: [
        "El estadio III implica pérdida total del espesor de la piel con tejido adiposo visible o cavidad.",
        "El nivel de exudado orienta la elección de coberturas con mayor absorción.",
      ],
      prevention: [
        "No basta la curación local: nutrición, descarga y manejo de humedad son parte del tratamiento.",
        "La vigilancia de olor y eritema perilesional ayuda a detectar complicaciones.",
      ],
      differentiation:
        "No es no clasificable porque el lecho puede verse; tampoco estadio IV porque no hay hueso ni tendón expuestos.",
    },
    outcome: {
      improvement: "Disminuye el exudado y se estabiliza la piel perilesional con buena protección.",
      stable: "Persiste cavidad superficial sin aumento de tamaño, pero requiere seguimiento estrecho.",
      worsening: "Incrementa exudado y dolor, con riesgo de infección local y progresión de profundidad.",
    },
  },
  {
    id: "lpp-unstageable",
    name: "Caso 5: Lesión no clasificable",
    difficulty: "advanced",
    summary: "Lesión en talón cubierta por esfacelos y necrosis que impiden valorar profundidad real.",
    learningObjective: "Identificar una lesión no clasificable y evitar clasificarla erróneamente como estadio III o IV.",
    estimatedMinutes: 16,
    patient: {
      age: 76,
      sex: "Femenino",
      context: "Paciente con ictus reciente, hemiplejia y bajo nivel de conciencia.",
      relevantHistory: ["Enfermedad vascular periférica", "Desnutrición", "Inmovilidad severa"],
      mobility: "Dependencia total.",
      nutrition: "Ingesta muy reducida; soporte enteral parcial.",
      hydration: "Mucosas secas, control estricto de balance.",
      continence: "Continencia no valorable; usa pañal absorbente.",
      perfusion: "Perfusión distal muy disminuida.",
      timeInBed: "Prácticamente todo el día en cama.",
      devices: ["Talonera improvisada mal posicionada"],
      pain: "Dolor difícil de valorar; gestos de molestia a la palpación.",
      vitals: {
        bloodPressure: "124/70 mmHg",
        heartRate: "90 lpm",
        respiratoryRate: "19 rpm",
        temperature: "37.1 °C",
        oxygenSaturation: "96%",
      },
      braden: {
        score: 8,
        interpretation: "Riesgo muy alto.",
      },
      caseGoal: "Usar razonamiento clínico para evitar una clasificación precipitada y reforzar prevención intensiva.",
    },
    wound: {
      location: "Talón izquierdo",
      bodySite: "heel",
      locationLabel: "Talón izquierdo",
      lengthCm: 4.3,
      widthCm: 3.7,
      depthCm: 0.9,
      edges: "Irregulares",
      tissue: "Esfacelos o necrosis que ocultan el lecho",
      exudate: "Escaso",
      odor: "Leve",
      periwoundSkin: "Frágil",
      pain: "Dolor leve",
      infectionSigns: ["Aumento de temperatura local"],
      hasSlough: true,
      hasNecrosis: true,
      stage: "No clasificable",
      hotspots: [
        { id: "cover", label: "Cobertura", description: "Escara y esfacelos impiden ver la profundidad real del lecho.", x: 52, y: 59 },
        { id: "edge", label: "Borde", description: "Bordes irregulares con piel frágil alrededor.", x: 66, y: 64 },
        { id: "perfusion", label: "Perfusión", description: "Talón con perfusión comprometida y alto riesgo de deterioro.", x: 38, y: 53 },
      ],
      differentialNote: "No puedes asignar estadio III o IV si la cobertura tisular impide valorar la verdadera profundidad; primero debes reconocerla como no clasificable.",
      visual: {
        imageSrc: "/medical-assets/wound-care/lpp/medetec-pressure-ulcer-heel.jpg",
        imageAlt: "Base clínica de talón con overlay didáctico para lesión no clasificable.",
        imageSourceLabel: MEDETEC_SOURCE,
        objectPosition: "center center",
        photoOpacity: 0.64,
        overlayTone: "unstageable",
        focus: { x: 52, y: 60, width: 36, height: 26, rotation: 8 },
        notes: [
          "Se reutiliza base clínica de talón y el overlay añade cobertura necrótica para lectura no clasificable.",
          "La prioridad visual está en tejido oculto y perfusión comprometida.",
        ],
      },
    },
    expected: {
      reviewedDomains: ["mobility", "nutrition", "hydration", "perfusion", "timeInBed", "devices", "pain", "braden"],
      riskFactors: ["immobility", "malnutrition", "poor-perfusion", "device-pressure", "low-braden"],
      priorityAlerts: ["deep-loss", "infection"],
      materialIds: ["hand-hygiene", "clean-gloves", "gauze", "saline", "skin-barrier", "foam-dressing", "waste", "positioning-aid", "adhesive-mesh"],
      inappropriateMaterialIds: ["alcohol", "dry-cotton", "hydrocolloid"],
      procedureSequence: [
        "hand-hygiene-start",
        "explain-patient",
        "prepare-position",
        "remove-old-dressing",
        "reassess-on-removal",
        "cleanse",
        "protect-periwound",
        "apply-cover",
        "secure-dressing",
        "dispose-waste",
        "hand-hygiene-end",
        "document-care",
      ],
      preventionIds: ["turning-schedule", "pressure-relief", "nutrition-support", "infection-watch", "reassessment", "caregiver-education"],
      documentationChecklist: ["location", "classification", "woundBed", "exudate", "odor", "pain", "intervention", "dressing", "followUpPlan"],
      classificationKeywords: ["esfacelo", "necrosis", "profundidad oculta", "no visible"],
    },
    education: {
      fundamentals: [
        "Una lesión no clasificable oculta su profundidad por esfacelos o escara.",
        "Clasificarla como estadio III o IV sin visualizar base completa es un error importante.",
      ],
      prevention: [
        "Descarga absoluta del talón y vigilancia de perfusión son prioritarias.",
        "La prevención sigue siendo obligatoria incluso cuando la lesión ya está establecida.",
      ],
      differentiation:
        "La lesión tisular profunda suele ser de coloración violácea o ampolla hemática con piel intacta; aquí ya existe pérdida de cobertura con tejido oculto por esfacelos/necrosis.",
    },
    outcome: {
      improvement: "La lesión se mantiene cubierta y protegida sin signos de deterioro adicional.",
      stable: "No hay cambios notorios, pero continúa la incertidumbre sobre profundidad real.",
      worsening: "Aumentan olor, dolor y deterioro local por mala descarga y vigilancia insuficiente.",
    },
  },
];

export function getWoundCaseById(caseId: string) {
  return WOUND_LPP_CASES.find((item) => item.id === caseId) ?? null;
}
